export const SUPPORTED_LOCALES = ['en', 'ko', 'ja', 'zh'] as const;

export type UiLocale = (typeof SUPPORTED_LOCALES)[number];

interface LabelValueCopy {
  label: string;
  value: string;
}

interface ProfileSettingsCopy {
  title: string;
  items: {
    language: LabelValueCopy;
    notifications: LabelValueCopy;
    offlineMaps: LabelValueCopy;
    mapData: LabelValueCopy;
  };
}

interface DocentProximityCopy {
  title: string;
  radiusLabel: string;
  checkButton: string;
  checking: string;
  ready: string;
  far: string;
  distanceLabel: string;
  noCoordinates: string;
  unsupported: string;
  denied: string;
  timeout: string;
  error: string;
}

interface LocationStatusCopy {
  lastKnownLocation: string;
}

interface DataSourceCopy {
  tourApi: string;
  cache: string;
  mock: string;
}

interface NetworkStatusCopy {
  offlineTitle: string;
  offlineBody: string;
}

interface PwaInstallCopy {
  title: string;
  body: string;
  install: string;
  dismiss: string;
  close: string;
}

export const LANGUAGE_NAMES: Record<UiLocale, string> = {
  en: 'English',
  ko: '한국어',
  ja: '日本語',
  zh: '简体中文',
};

const UI_COPY = {
  en: {
    common: {
      appName: 'K-Vibe Tracker',
      signIn: 'Sign in',
      close: 'Close',
      goBack: 'Go back',
      changeLanguage: 'Change language',
      openProfile: 'Open profile',
      avatarAlt: 'User avatar',
      unexpectedErrorTitle: 'Something went wrong',
      unexpectedErrorBody: 'An unexpected error occurred. Please try again.',
      reloadPage: 'Reload Page',
      dismissNotification: 'Dismiss notification',
    },
    login: {
      eyebrow: 'Account',
      title: 'Sign in to K-Vibe',
      subtitle: 'Save routes and sync preferences when Supabase is configured.',
      close: 'Close sign in',
      continueGoogle: 'Continue with Google',
      continueGuest: 'Continue as Guest',
      availableWithoutLogin: 'Available without login',
      loginRequiredLater: 'Login required later: saved routes, sharing history, account sync',
      supabaseMissing: 'Supabase env is not configured. Continue as Guest for local development.',
      failed: 'Login failed. Please try again.',
      guestFeatures: [
        'Map exploration and place search',
        'SNS spot analyzer',
        'Route generation preview',
        'Facility radar',
      ],
    },
    landing: {
      eyebrow: 'Local-first travel lab',
      languageTitle: 'Choose your language',
      description:
        'Discover Korea through K-content inspired places, routes, and nearby travel helpers. TourAPI place data is used when a key is configured, with safe local fallbacks for development.',
      start: 'Explore K-Vibe',
      guestNotice: 'Map, Analyze, Route, and Radar work without login.',
      developmentMode: 'Development mode',
      developmentDescription:
        'External services stay behind explicit keys or approval gates, while core workflows remain testable locally.',
      trendingLabel: 'Trending prompts',
      trendingTags: ['Seongsu cafes', 'Gwangjang food', 'Palace drama', 'Hongdae photo', 'Han River night'],
      features: {
        map: 'TourAPI nearby spots',
        analyze: 'Local-first SNS extraction',
        route: 'Persona route planner',
        radar: 'Facility finder',
      },
    },
    homeFeed: {
      eyebrow: 'Live Seoul feed',
      title: 'Trending K-spots nearby',
      stories: {
        kpop: 'K-Pop',
        streetFood: 'Street Food',
        photoSpots: 'Photo Spots',
        nature: 'Nature',
        shopping: 'Shopping',
      },
      refresh: 'Refresh feed',
      openMap: 'Open in Map',
      openPlaceDetail: 'Open {name} details',
      empty: 'No feed places found for this filter.',
      emptyHint: 'Reset the filter or continue discovery on the map.',
      showAll: 'Show all',
      exploreMap: 'Explore map',
      error: 'Home feed could not be loaded',
      retry: 'Retry',
      cachedFallback: 'Showing cached feed because live refresh failed.',
      sourceTourapi: 'TourAPI',
      sourceCache: 'Cache',
      sourceMock: 'Mock',
      personalizedFor: 'For {persona}',
    },
    nav: {
      map: 'Map',
      analyze: 'Analyze',
      route: 'Route',
      radar: 'Radar',
      profile: 'Profile',
    },
    categories: {
      all: 'All',
      cafe: 'Cafe',
      photo: 'Photo',
      fun: 'Fun',
      culture: 'Culture',
      food: 'Food',
      stay: 'Stay',
      spot: 'Spot',
    },
    map: {
      seoulFallback: 'Seoul fallback',
      currentLocation: 'Current location',
      locationUnavailable: 'Location permission is unavailable. Showing a saved or fallback position.',
      analysisResult: 'Analysis result',
      searchPlaceholder: 'Search places',
      loadingNearby: 'Loading nearby places',
      placesError: 'Places could not be loaded',
      retry: 'Retry',
      noPlaces: 'No places found',
      noPlacesHint: 'Clear the search or reset filters to bring nearby places back.',
      resetFilters: 'Reset filters',
      nearbySpots: 'Nearby spots',
      resultCount: '{count} shown',
      addressPending: 'Address pending',
      addedFromMap: 'Added from the map as a {category} stop.',
      radiusLabel: 'km radius',
      refreshLocation: 'Refresh current location',
      openAnalyzer: 'Open SNS analyzer',
      savedRouteTitle: 'Map Saved Route',
      savedRouteSummary: 'Custom route assembled from map selections.',
      crowd: {
        low: 'Quiet',
        mid: 'Normal',
        high: 'Busy',
      },
    },
    placeDetail: {
      addToRoute: 'Add to Route',
      addedToRoute: 'Added to route',
      save: 'Save place',
      saved: 'Saved place',
      removed: 'Removed from saved places',
      docent: 'Docent',
      details: 'Details',
      parking: 'Parking',
      loadingDetail: 'Loading TourAPI detail',
      detailFallback: 'Detail fallback active',
      closeDetail: 'Close place detail',
      imagePreview: 'Preview image {index}',
      seenInTitle: 'Seen in',
      seenInYoutube: 'YouTube {count} videos',
      seenInInstagram: 'Instagram {count} posts',
      share: 'Share',
      shared: 'Shared',
      copied: 'Copied link',
      shareUnavailable: 'Share unavailable',
      crowd: {
        low: 'Quiet',
        mid: 'Normal',
        high: 'Busy',
      },
    },
    analyze: {
      title: 'SNS Spot Analyzer',
      subtitle:
        'Paste a YouTube or Instagram URL. YouTube uses local mock analysis until AI is approved; Instagram is detected but not analyzed yet.',
      inputPlaceholder: 'Paste a YouTube or Instagram URL',
      invalidUrl: 'This does not look like a supported YouTube URL.',
      unsupportedUrl: 'Paste a supported YouTube or Instagram URL.',
      youtubeSupported: 'YouTube ready',
      instagramPending: 'Instagram queued',
      instagramPendingTitle: 'Instagram analysis is approval-gated',
      instagramPendingBody:
        'The app can now detect Instagram links, but live Instagram extraction is held until a no-cost or approved provider path is available.',
      thumbnailAlt: 'YouTube thumbnail',
      analyzeButton: 'Analyze Spots',
      loadingButton: 'Analyzing spots...',
      examplesLabel: 'Example URLs',
      loadingTitle: 'Analysis in progress',
      loadingEstimate: 'Local analysis usually finishes in a few seconds. Enabled AI workers can take 10-20 seconds on cold start.',
      loadingColdStart: 'If this takes longer, the worker may still be waking up.',
      loadingSteps: ['Validating URL', 'Reading video context', 'Matching candidate places', 'Preparing map-ready results'],
      errorTitle: 'Analysis failed',
      retry: 'Retry',
      foundSpots: 'Found {count} candidate spots',
      emptyTitle: 'No clear places found',
      emptyBody: 'Try a travel vlog, MV location clip, or one of the sample URLs above.',
      tryExample: 'Try a sample YouTube URL',
      sourceWorker: 'AI Worker',
      sourceMock: 'Mock',
      sourceCache: 'Previous result',
      confidence: 'confidence',
      map: 'Map',
      viewOnMap: 'View on Map',
      buildRoute: 'Build Route',
      localModeTitle: 'Local-first analysis',
      localModeBody:
        'The API returns deterministic mock spot extraction unless an approved AI worker URL is explicitly configured.',
      openVideo: 'Open video',
      openPost: 'Open post',
      detectedAddress: 'Detected from YouTube analysis',
      routeTitle: 'SNS Analysis Route',
      routeSummary: 'Route drafted from {title}.',
      routeSaved: 'Route saved',
      routeSaveFailed: 'Route could not be saved',
    },
    radar: {
      title: 'Facility Radar',
      locationSeoul: 'Seoul fallback',
      locationCurrent: 'Current location',
      locationUnavailable: 'Location permission is unavailable. Showing saved or fallback facilities.',
      found: '{count} found',
      refresh: 'Refresh facilities',
      radius: 'Radius',
      sourceMock: 'Mock',
      mapTitle: 'Radar map',
      mapSubtitle: '{radius}m radius preview',
      currentPosition: 'Current position',
      openFacilityMap: 'Open {name} in Google Maps',
      filters: {
        all: 'All',
        restroom: 'Restroom',
        atm: 'ATM',
        medical: 'Medical',
        transit: 'Transit',
        cafe_toilet: 'Cafe WC',
        pharmacy: 'Pharmacy',
        convenience: 'Store',
        popup: 'Pop-up',
      },
      facilityTypes: {
        restroom: 'Restroom',
        atm: 'ATM',
        medical: 'Medical',
        transit: 'Transit',
        pharmacy: 'Pharmacy',
        cafe_toilet: 'Cafe restroom',
        convenience: 'Convenience',
        popup: 'Pop-up',
      },
      errorTitle: 'Facilities could not be loaded',
      retry: 'Retry',
      loading: 'Scanning nearby facilities',
      emptyTitle: 'No facilities found in this radius',
      emptyHint: 'Increase the radius or try another category.',
      expandRadius: 'Expand radius',
      closed: 'Closed',
      twentyFourHours: '24h',
      accessibleRestroom: 'Accessible restroom available',
      viewOnMap: 'View on Map',
      footer: 'Local mock data is used during development. Live facility sources are approval-gated.',
    },
    profile: {
      title: 'Profile',
      guestTitle: 'Guest traveler',
      guestSubtitle: 'Local guest mode keeps map, route, and saved places usable without Supabase.',
      signInTitle: 'Sign in to sync trips',
      signInDescription: 'Account sync is enabled after Supabase credentials are configured.',
      supabaseNotConfigured: 'Supabase not configured',
      supabaseDescription:
        'Login is intentionally disabled until NEXT_PUBLIC_SUPABASE_URL and NEXT_PUBLIC_SUPABASE_ANON_KEY are provided.',
      savedPlaces: 'Saved Places',
      noSavedPlaces: 'No saved places yet',
      noSavedPlacesHint: 'Open the map, choose a place, and tap the heart.',
      savedRoutes: 'Saved routes',
      noSavedRoutes: 'No saved route yet',
      noSavedRoutesHint: 'Generate or assemble a route to keep it in local storage.',
      createFirstRoute: 'Create your first route',
      currentRoute: 'Current local route',
      editRoute: 'Edit route',
      continueRoute: 'Continue',
      routeProgress: '{done}/{total} complete',
      nextStop: 'Next stop',
      routeComplete: 'Route complete',
      openMap: 'Open in Map',
      openSavedDetail: 'Open {name} details',
      openSavedDetailCta: 'View details',
      openRouteDetail: 'Open {name} route',
      openRouteDetailCta: 'Open route detail',
      statsPlaces: 'Places',
      statsRoutes: 'Routes',
      seeAll: 'See all',
      showLess: 'Show less',
      settings: 'Settings',
      personaLabel: 'Persona',
      personaUnset: 'Not selected',
      signInGoogle: 'Sign in with Google',
      signOut: 'Sign out',
      routeStops: '{count} stops',
    },
    route: {
      title: 'Route',
      editableEyebrow: 'Editable itinerary',
      helper: 'Drag stops to reorder. Local save/auth sync is approval-gated.',
      stops: 'Stops',
      done: 'Done',
      walking: 'Walking',
      total: 'Total',
      miniMapTitle: 'Route map preview',
      miniMapSubtitle: 'Tap a stop number to open it in Google Maps.',
      travelSegment: 'Walk {duration} · {distance}',
      transitSegment: 'Transit {duration} · {distance}',
      travelSegmentBetween: '{from} to {to}',
      locationCardTitle: 'Current distance',
      locationCardBody: 'Check your current distance to {name} when you are ready to move.',
      checkCurrentLocation: 'Check location',
      checkingLocation: 'Checking...',
      nextStopNear: 'You are within {distance} of {name}. Start the local docent when ready.',
      nextStopFar: '{name} is {distance} away. Keep following your route.',
      locationPermissionDenied: 'Location permission was denied. You can still use the route manually.',
      locationUnsupported: 'Location is not available in this browser.',
      locationCheckError: 'Current location could not be checked. Try again later.',
      staySuffix: 'min stay',
      orderUpdated: 'Route order updated',
      stopRemoved: 'Stop removed',
      sampleStopAdded: 'Sample stop added',
      stopCompleted: 'Stop marked complete',
      stopReopened: 'Stop reopened',
      routeCompleted: 'All stops are complete',
      addStopBeforeGuidance: 'Add a stop before starting guidance',
      shared: 'Shared',
      copiedSummary: 'Copied route summary',
      shareUnavailable: 'Share unavailable',
      sharedRouteLoaded: 'Shared route loaded',
      addSampleStop: 'Add sample stop',
      openRouteMap: 'Open in Map',
      openRouteMapTitle: 'Open the full route in the app map',
      openDirections: 'Open Directions',
      directionsOpened: 'Opened walking directions',
      startGuidance: 'Start Guidance',
      share: 'Share',
      openStopDetail: 'Open {name} details in the app map',
      openStopDetailTitle: 'Open place detail',
      openStopMap: 'Open {name} in Google Maps',
      openStopMapTitle: 'Open in Google Maps',
      openDocent: 'Open docent for {name}',
      openDocentTitle: 'Open docent',
      completed: 'Done',
      markComplete: 'Mark {name} complete',
      markIncomplete: 'Reopen {name}',
      markCompleteTitle: 'Mark complete',
      markIncompleteTitle: 'Reopen stop',
      moveStopUp: 'Move {name} up',
      moveStopDown: 'Move {name} down',
      moveStopUpTitle: 'Move up',
      moveStopDownTitle: 'Move down',
      removeStop: 'Remove {name}',
      extraStop: {
        id: 'cheonggyecheon-stream',
        name: 'Cheonggyecheon Stream',
        category: 'Walk',
        address: 'Jongno-gu, Seoul',
        description: 'A flexible walking stop that fits between old Seoul and evening neighborhoods.',
        tags: ['walk', 'river'],
      },
    },
    persona: {
      previewEyebrow: 'Local route preview',
      createAnother: 'Create another route',
      stops: 'Stops',
      walking: 'Walking',
      total: 'Total',
      editRoute: 'Edit Route',
      share: 'Share',
      shared: 'Shared',
      copied: 'Copied',
      shareUnavailable: 'Share unavailable',
      routeGenerated: 'Route preview ready',
      routeSaved: 'Route saved for editing',
      routeSaveUnavailable: 'Route could not be saved',
      personaSaveUnavailable: 'Feed could not be personalized',
      generatorEyebrow: 'Route generator',
      title: 'Build a K-content day plan',
      subtitle: 'Pick a theme and route mood. This local generator is deterministic while paid AI is approval-gated.',
      startTime: 'Start time',
      backToThemes: 'Back to route themes',
      backToMoods: 'Back to route moods',
      chooseMood: 'Choose the route mood',
      reviewSelection: 'Review Selection',
      confirmEyebrow: 'Confirm route inputs',
      confirmTitle: 'Ready to generate?',
      confirmBody: 'Review your route ingredients before creating the local preview plan.',
      selectedTheme: 'Theme',
      selectedDetail: 'Mood',
      selectedStart: 'Start',
      adjustSelection: 'Adjust selection',
      personalizeFeed: 'Personalize Feed',
      personaSaved: 'Feed personalized',
      generating: 'Generating route...',
      generate: 'Generate Route',
      routeTitle: '{detail} Seoul Route',
      routeSummary: '{themeDescription} Planned as a {duration} local preview route.',
      themes: {
        kpop: {
          label: 'K-pop Pilgrimage',
          description: 'Agency streets, fan photo spots, music stores, and night views.',
          details: {
            bts: { label: 'BTS', description: 'HYBE, merch streets, and fan-friendly stops.' },
            blackpink: { label: 'BLACKPINK', description: 'Style-led stops with shopping and photos.' },
            newjeans: { label: 'NewJeans', description: 'Retro, cafe, and photo-forward places.' },
            aespa: { label: 'aespa', description: 'Futuristic spots and high-energy neighborhoods.' },
          },
        },
        drama: {
          label: 'K-drama Scenes',
          description: 'Palaces, alleys, markets, and cinematic walking routes.',
          details: {
            palace: { label: 'Palace drama', description: 'Historic Seoul with classic filming moods.' },
            romance: { label: 'Romance walk', description: 'Soft scenery, cafes, and evening lights.' },
            street_food: { label: 'Street food story', description: 'Markets and snack-heavy drama energy.' },
            night: { label: 'Night episode', description: 'Bridges, towers, and after-dark city shots.' },
          },
        },
        mood: {
          label: 'Mood Travel',
          description: 'Aesthetic Seoul routes tuned for pace, photos, and recovery time.',
          details: {
            cafe: { label: 'Cafe day', description: 'Cafe streets, design shops, and slower pacing.' },
            photo: { label: 'Photo walk', description: 'Color, texture, and easy photo stops.' },
            healing: { label: 'Healing', description: 'Parks, riverside walks, and lower crowd pressure.' },
            food: { label: 'Food crawl', description: 'Markets, snacks, and dinner-friendly routing.' },
          },
        },
        foodie: {
          label: 'Foodie Explorer',
          description: 'Street food, markets, desserts, and late meals in a walkable day.',
          details: {
            market: { label: 'Market tasting', description: 'Classic alleys, small bites, and lively stalls.' },
            dessert: { label: 'Dessert hop', description: 'Cafes, bakeries, and sweet photo stops.' },
            night_food: { label: 'Night food', description: 'Dinner, neon streets, and easy final transit.' },
            local_table: { label: 'Local table', description: 'Comfort food, tea, and slower neighborhood pacing.' },
          },
        },
        creator: {
          label: 'Content Creator',
          description: 'Photogenic backdrops, design streets, and short-form-friendly stops.',
          details: {
            reels: { label: 'Reels walk', description: 'Compact spots with quick transitions and texture.' },
            fashion: { label: 'Fashion street', description: 'Style-led neighborhoods and boutique windows.' },
            design: { label: 'Design frame', description: 'Architecture, galleries, and clean composition.' },
            night_shot: { label: 'Night shots', description: 'Lights, reflections, and skyline-friendly pacing.' },
          },
        },
        history: {
          label: 'History Buff',
          description: 'Palaces, hanok alleys, museums, and heritage-focused walking routes.',
          details: {
            palace_day: { label: 'Palace day', description: 'Royal sites, gates, and hanbok-friendly timing.' },
            hanok_walk: { label: 'Hanok walk', description: 'Traditional alleys with tea and craft stops.' },
            museum: { label: 'Museum route', description: 'Indoor culture stops for weather-safe exploring.' },
            heritage_food: { label: 'Heritage food', description: 'Old Seoul streets with classic market meals.' },
          },
        },
      },
    },
    docent: {
      title: 'AI Docent',
      eyebrow: 'Local voice guide',
      localMode: 'Browser voice',
      captionTitle: 'Caption',
      progressLabel: 'Script progress',
      progressValue: 'Section {current}/{total}',
      sectionIntroTitle: 'Intro',
      sectionBodyTitle: 'Details',
      sectionTagsTitle: 'Look for',
      sectionOutroTitle: 'Next step',
      play: 'Play',
      pause: 'Pause',
      resume: 'Resume',
      stop: 'Stop',
      replay: 'Replay',
      backToRoute: 'Back to route',
      textOnly: 'Text-only mode',
      audioUnavailable: 'This browser cannot play local speech here.',
      fallbackName: 'Selected stop',
      fallbackAddress: 'Address pending',
      fallbackCategory: 'Travel stop',
      defaultDescription: 'This stop is part of your current K-vibe route.',
      scriptIntro: '{name} is a {category} stop on your route.',
      scriptBody: '{description} You will spend about {stayMinutes} minutes here. The address is {address}.',
      scriptTags: 'Good cues for this stop: {tags}.',
      scriptOutro: 'Take a moment to look around, then continue when the timing feels right.',
    },
    tutorial: {
      buttonLabel: 'Feature guide',
      title: 'Feature Guide',
      subtitle: 'A quick tour of what you can use in this MVP.',
      footer: 'Paid or permission-gated integrations stay disabled until credentials are approved.',
      steps: [
        {
          title: 'Map',
          body: 'Find nearby places from TourAPI or mock fallback data, filter categories, inspect details, and add a spot to your route.',
          action: 'Open Map',
        },
        {
          title: 'Analyze',
          body: 'Paste a YouTube or Instagram URL to test platform detection. YouTube mock analysis stays usable without AI costs.',
          action: 'Try Analyze',
        },
        {
          title: 'Route',
          body: 'Generate a persona-based route, edit stops, reorder the timeline, and share the plan text.',
          action: 'Build Route',
        },
        {
          title: 'Docent',
          body: 'Open a route stop as a local voice guide with captions. It uses browser speech synthesis, not a paid TTS API.',
          action: 'Open Route',
        },
        {
          title: 'Radar',
          body: 'Search nearby convenience facilities with radius/type filters and clear source hints.',
          action: 'Open Radar',
        },
        {
          title: 'Profile',
          body: 'Use guest mode now; Supabase sync and saved account history activate when credentials are configured.',
          action: 'Open Profile',
        },
      ],
    },
  },
  ko: {
    common: {
      appName: 'K-Vibe Tracker',
      signIn: '로그인',
      close: '닫기',
      goBack: '뒤로 가기',
      changeLanguage: '언어 변경',
      openProfile: '프로필 열기',
      avatarAlt: '사용자 아바타',
      unexpectedErrorTitle: '문제가 발생했어요',
      unexpectedErrorBody: '예상하지 못한 오류가 발생했습니다. 다시 시도해 주세요.',
      reloadPage: '페이지 새로고침',
      dismissNotification: '알림 닫기',
    },
    login: {
      eyebrow: '계정',
      title: 'K-Vibe에 로그인',
      subtitle: 'Supabase가 설정되면 루트를 저장하고 취향을 동기화할 수 있어요.',
      close: '로그인 닫기',
      continueGoogle: 'Google로 계속하기',
      continueGuest: '게스트로 계속하기',
      availableWithoutLogin: '로그인 없이 사용 가능',
      loginRequiredLater: '나중에 로그인 필요: 저장 루트, 공유 기록, 계정 동기화',
      supabaseMissing: 'Supabase 환경 변수가 설정되지 않았습니다. 로컬 개발에서는 게스트로 계속 사용할 수 있어요.',
      failed: '로그인에 실패했습니다. 다시 시도해 주세요.',
      guestFeatures: [
        '지도 탐색과 장소 검색',
        'SNS 스팟 분석',
        '루트 생성 미리보기',
        '편의시설 레이더',
      ],
    },
    landing: {
      eyebrow: '로컬 우선 여행 실험실',
      languageTitle: '언어를 선택하세요',
      description:
        'K-콘텐츠 감성의 장소, 루트, 주변 편의 정보를 통해 한국 여행을 발견하세요. 키가 설정되면 TourAPI 장소 데이터를 사용하고, 개발 중에는 안전한 로컬 대체 데이터를 유지합니다.',
      start: 'K-Vibe 둘러보기',
      guestNotice: '지도, 분석, 루트, 레이더는 로그인 없이 사용할 수 있어요.',
      developmentMode: '개발 모드',
      developmentDescription:
        '외부 서비스는 키나 승인 게이트 뒤에 두고, 핵심 흐름은 로컬에서 계속 테스트할 수 있게 유지합니다.',
      trendingLabel: '추천 탐색어',
      trendingTags: ['성수 카페', '광장시장 먹거리', '궁궐 드라마', '홍대 포토', '한강 야경'],
      features: {
        map: 'TourAPI 주변 장소',
        analyze: '로컬 우선 SNS 분석',
        route: '페르소나 루트 플래너',
        radar: '편의시설 찾기',
      },
    },
    homeFeed: {
      eyebrow: '서울 실시간 피드',
      title: '지금 뜨는 K-스팟',
      stories: {
        kpop: 'K-Pop',
        streetFood: '길거리 음식',
        photoSpots: '포토 스팟',
        nature: '자연',
        shopping: '쇼핑',
      },
      refresh: '피드 새로고침',
      openMap: '지도에서 보기',
      openPlaceDetail: '{name} 상세 보기',
      empty: '이 필터에 맞는 피드 장소가 없어요.',
      emptyHint: '필터를 초기화하거나 지도에서 계속 탐색해보세요.',
      showAll: '전체 보기',
      exploreMap: '지도 탐색',
      error: '홈 피드를 불러오지 못했습니다',
      retry: '다시 시도',
      cachedFallback: '실시간 새로고침에 실패해 캐시된 피드를 표시합니다.',
      sourceTourapi: 'TourAPI',
      sourceCache: '캐시',
      sourceMock: 'Mock',
      personalizedFor: '{persona} 맞춤',
    },
    nav: {
      map: '지도',
      analyze: '분석',
      route: '루트',
      radar: '레이더',
      profile: '프로필',
    },
    categories: {
      all: '전체',
      cafe: '카페',
      photo: '사진',
      fun: '즐길거리',
      culture: '문화',
      food: '음식',
      stay: '숙소',
      spot: '장소',
    },
    map: {
      seoulFallback: '서울 기본 위치',
      currentLocation: '현재 위치',
      locationUnavailable: '위치 권한을 사용할 수 없어 저장된 위치나 기본 위치를 표시합니다.',
      analysisResult: '분석 결과 위치',
      searchPlaceholder: '장소 검색',
      loadingNearby: '주변 장소를 불러오는 중',
      placesError: '장소를 불러오지 못했습니다',
      retry: '다시 시도',
      noPlaces: '장소를 찾지 못했습니다',
      noPlacesHint: '검색어를 지우거나 필터를 초기화해 주변 장소를 다시 확인하세요.',
      resetFilters: '필터 초기화',
      nearbySpots: '주변 장소',
      resultCount: '{count}개 표시',
      addressPending: '주소 확인 중',
      addedFromMap: '지도에서 {category} 방문지로 추가했어요.',
      radiusLabel: 'km 반경',
      refreshLocation: '현재 위치 새로고침',
      openAnalyzer: 'SNS 분석 열기',
      savedRouteTitle: '지도 저장 루트',
      savedRouteSummary: '지도에서 선택한 장소로 만든 맞춤 루트입니다.',
      crowd: {
        low: '여유',
        mid: '보통',
        high: '혼잡',
      },
    },
    placeDetail: {
      addToRoute: '루트에 추가',
      addedToRoute: '루트에 추가했어요',
      save: '장소 저장',
      saved: '저장된 장소',
      removed: '저장 장소에서 제거했어요',
      docent: '도슨트',
      details: '상세',
      parking: '주차',
      loadingDetail: 'TourAPI 상세 불러오는 중',
      detailFallback: '상세 대체 모드',
      closeDetail: '장소 상세 닫기',
      imagePreview: '{index}번째 이미지 보기',
      seenInTitle: '콘텐츠 노출',
      seenInYoutube: 'YouTube 영상 {count}개',
      seenInInstagram: 'Instagram 게시물 {count}개',
      share: '공유',
      shared: '공유했어요',
      copied: '링크를 복사했어요',
      shareUnavailable: '공유할 수 없어요',
      crowd: {
        low: '여유',
        mid: '보통',
        high: '혼잡',
      },
    },
    analyze: {
      title: 'SNS 스팟 분석',
      subtitle:
        'YouTube 또는 Instagram URL을 붙여 넣으세요. YouTube는 AI 승인 전까지 로컬 mock 분석을 사용하고, Instagram은 감지만 지원합니다.',
      inputPlaceholder: 'YouTube 또는 Instagram URL 붙여넣기',
      invalidUrl: '지원되는 YouTube URL 형식이 아니에요.',
      unsupportedUrl: '지원되는 YouTube 또는 Instagram URL을 붙여 넣어주세요.',
      youtubeSupported: 'YouTube 준비됨',
      instagramPending: 'Instagram 대기 중',
      instagramPendingTitle: 'Instagram 분석은 승인 대기 중입니다',
      instagramPendingBody:
        '앱이 Instagram 링크를 감지할 수는 있지만, 실제 Instagram 장소 추출은 무료 또는 승인된 provider 경로가 준비될 때까지 보류합니다.',
      thumbnailAlt: 'YouTube 썸네일',
      analyzeButton: '스팟 분석',
      loadingButton: '스팟 분석 중...',
      examplesLabel: '예시 URL',
      loadingTitle: '분석 진행 중',
      loadingEstimate: '로컬 분석은 보통 몇 초 안에 끝납니다. AI worker가 켜진 경우 콜드스타트에 10-20초가 걸릴 수 있어요.',
      loadingColdStart: '오래 걸리면 worker 서버가 깨어나는 중일 수 있습니다.',
      loadingSteps: ['URL 확인 중', '영상 맥락 읽는 중', '후보 장소 매칭 중', '지도에 보낼 결과 준비 중'],
      errorTitle: '분석 실패',
      retry: '다시 시도',
      foundSpots: '후보 스팟 {count}개를 찾았어요',
      emptyTitle: '뚜렷한 장소를 찾지 못했어요',
      emptyBody: '여행 브이로그, MV 촬영지 영상, 또는 위 예시 URL로 다시 시도해보세요.',
      tryExample: '예시 YouTube URL로 시도',
      sourceWorker: 'AI Worker',
      sourceMock: 'Mock',
      sourceCache: '이전 결과',
      confidence: '신뢰도',
      map: '지도',
      viewOnMap: '지도에서 보기',
      buildRoute: '루트 만들기',
      localModeTitle: '로컬 우선 분석',
      localModeBody:
        '승인된 AI worker URL을 명시적으로 설정하기 전까지 API는 결정적인 mock 스팟 추출 결과를 반환합니다.',
      openVideo: '영상 열기',
      openPost: '게시물 열기',
      detectedAddress: 'YouTube 분석에서 감지됨',
      routeTitle: 'SNS 분석 루트',
      routeSummary: '{title}에서 만든 초안 루트입니다.',
      routeSaved: '루트를 저장했어요',
      routeSaveFailed: '루트를 저장할 수 없어요',
    },
    radar: {
      title: '편의시설 레이더',
      locationSeoul: '서울 기본 위치',
      locationCurrent: '현재 위치',
      locationUnavailable: '위치 권한을 사용할 수 없어 저장된 위치나 기본 위치의 편의시설을 표시합니다.',
      found: '{count}개 발견',
      refresh: '편의시설 새로고침',
      radius: '반경',
      sourceMock: 'Mock',
      mapTitle: '레이더 지도',
      mapSubtitle: '{radius}m 반경 미리보기',
      currentPosition: '현재 위치',
      openFacilityMap: 'Google Maps에서 {name} 열기',
      filters: {
        all: '전체',
        restroom: '화장실',
        atm: 'ATM',
        medical: '의료',
        transit: '교통',
        cafe_toilet: '카페 화장실',
        pharmacy: '약국',
        convenience: '편의점',
        popup: '팝업',
      },
      facilityTypes: {
        restroom: '화장실',
        atm: 'ATM',
        medical: '의료',
        transit: '교통',
        pharmacy: '약국',
        cafe_toilet: '카페 화장실',
        convenience: '편의점',
        popup: '팝업스토어',
      },
      errorTitle: '편의시설을 불러오지 못했습니다',
      retry: '다시 시도',
      loading: '주변 편의시설을 찾는 중',
      emptyTitle: '이 반경 안에 편의시설이 없어요',
      emptyHint: '반경을 넓히거나 다른 카테고리를 선택해보세요.',
      expandRadius: '반경 넓히기',
      closed: '영업 종료',
      twentyFourHours: '24시간',
      accessibleRestroom: '장애인 이용 가능 화장실',
      viewOnMap: '지도에서 보기',
      footer: '개발 중에는 로컬 mock 데이터를 사용합니다. 실시간 편의시설 소스는 승인 후 연결합니다.',
    },
    profile: {
      title: '프로필',
      guestTitle: '게스트 여행자',
      guestSubtitle: 'Supabase 없이도 지도, 루트, 저장 장소를 로컬 게스트 모드로 사용할 수 있어요.',
      signInTitle: '로그인하면 여행을 동기화할 수 있어요',
      signInDescription: 'Supabase 정보가 설정되면 계정 동기화가 활성화됩니다.',
      supabaseNotConfigured: 'Supabase 미설정',
      supabaseDescription:
        'NEXT_PUBLIC_SUPABASE_URL과 NEXT_PUBLIC_SUPABASE_ANON_KEY가 제공되기 전까지 로그인은 의도적으로 비활성화됩니다.',
      savedPlaces: '저장 장소',
      noSavedPlaces: '아직 저장한 장소가 없어요',
      noSavedPlacesHint: '지도를 열고 장소를 선택한 뒤 하트를 눌러 저장하세요.',
      savedRoutes: '저장 루트',
      noSavedRoutes: '아직 저장된 루트가 없어요',
      noSavedRoutesHint: '루트를 생성하거나 지도에서 장소를 추가하면 로컬에 보관됩니다.',
      createFirstRoute: '첫 루트 만들기',
      currentRoute: '현재 로컬 루트',
      editRoute: '루트 편집',
      continueRoute: '이어가기',
      routeProgress: '{done}/{total} 완료',
      nextStop: '다음 방문지',
      routeComplete: '루트 완료',
      openMap: '지도에서 보기',
      openSavedDetail: '{name} 상세 보기',
      openSavedDetailCta: '상세 보기',
      openRouteDetail: '{name} 루트 열기',
      openRouteDetailCta: '루트 상세 열기',
      statsPlaces: '장소',
      statsRoutes: '루트',
      seeAll: '전체 보기',
      showLess: '접기',
      settings: '설정',
      personaLabel: '페르소나',
      personaUnset: '미선택',
      signInGoogle: 'Google로 로그인',
      signOut: '로그아웃',
      routeStops: '{count}개 장소',
    },
    route: {
      title: '루트',
      editableEyebrow: '편집 가능한 일정',
      helper: '방문지를 드래그해 순서를 바꾸세요. 로컬 저장은 가능하고 계정 동기화는 승인 후 활성화됩니다.',
      stops: '장소',
      done: '완료',
      walking: '도보',
      total: '전체',
      miniMapTitle: '루트 미니맵',
      miniMapSubtitle: '번호를 누르면 Google Maps에서 해당 장소를 열어요.',
      travelSegment: '도보 {duration} · {distance}',
      transitSegment: '대중교통 {duration} · {distance}',
      travelSegmentBetween: '{from}에서 {to}까지',
      locationCardTitle: '현재 거리',
      locationCardBody: '이동 준비가 되면 {name}까지의 현재 거리를 확인하세요.',
      checkCurrentLocation: '위치 확인',
      checkingLocation: '확인 중...',
      nextStopNear: '{name}까지 {distance} 이내예요. 준비되면 로컬 도슨트를 시작하세요.',
      nextStopFar: '{name}까지 {distance} 남았어요. 루트를 따라 계속 이동하세요.',
      locationPermissionDenied: '위치 권한이 거부됐어요. 루트는 수동으로 계속 사용할 수 있습니다.',
      locationUnsupported: '이 브라우저에서는 위치 확인을 사용할 수 없어요.',
      locationCheckError: '현재 위치를 확인하지 못했습니다. 잠시 후 다시 시도하세요.',
      staySuffix: '분 머무름',
      orderUpdated: '루트 순서를 업데이트했어요',
      stopRemoved: '방문지를 삭제했어요',
      sampleStopAdded: '샘플 방문지를 추가했어요',
      stopCompleted: '방문지를 완료 처리했어요',
      stopReopened: '방문지를 다시 열었어요',
      routeCompleted: '모든 방문지를 완료했어요',
      addStopBeforeGuidance: '가이드를 시작하려면 먼저 방문지를 추가하세요',
      shared: '공유했어요',
      copiedSummary: '루트 요약을 복사했어요',
      shareUnavailable: '공유할 수 없어요',
      sharedRouteLoaded: '공유 루트를 불러왔어요',
      addSampleStop: '샘플 방문지 추가',
      openRouteMap: '지도에서 보기',
      openRouteMapTitle: '앱 지도에서 전체 루트 보기',
      openDirections: '길찾기 열기',
      directionsOpened: '도보 길찾기를 열었어요',
      startGuidance: '가이드 시작',
      share: '공유',
      openStopDetail: '앱 지도에서 {name} 상세 열기',
      openStopDetailTitle: '장소 상세 열기',
      openStopMap: 'Google Maps에서 {name} 열기',
      openStopMapTitle: 'Google Maps에서 열기',
      openDocent: '{name} 도슨트 열기',
      openDocentTitle: '도슨트 열기',
      completed: '완료',
      markComplete: '{name} 완료 표시',
      markIncomplete: '{name} 다시 열기',
      markCompleteTitle: '완료 표시',
      markIncompleteTitle: '다시 열기',
      moveStopUp: '{name} 위로 이동',
      moveStopDown: '{name} 아래로 이동',
      moveStopUpTitle: '위로 이동',
      moveStopDownTitle: '아래로 이동',
      removeStop: '{name} 삭제',
      extraStop: {
        id: 'cheonggyecheon-stream',
        name: '청계천',
        category: '산책',
        address: '서울 종로구',
        description: '옛 서울과 저녁 동네 사이에 자연스럽게 넣기 좋은 유연한 산책 코스입니다.',
        tags: ['산책', '하천'],
      },
    },
    persona: {
      previewEyebrow: '로컬 루트 미리보기',
      createAnother: '다른 루트 만들기',
      stops: '장소',
      walking: '도보',
      total: '전체',
      editRoute: '루트 편집',
      share: '공유',
      shared: '공유했어요',
      copied: '복사했어요',
      shareUnavailable: '공유할 수 없어요',
      routeGenerated: '루트 미리보기가 준비됐어요',
      routeSaved: '편집할 루트를 저장했어요',
      routeSaveUnavailable: '루트를 저장할 수 없어요',
      personaSaveUnavailable: '피드를 개인화할 수 없어요',
      generatorEyebrow: '루트 생성기',
      title: 'K-콘텐츠 하루 루트 만들기',
      subtitle: '테마와 무드를 고르세요. 유료 AI 승인 전까지는 결정적인 로컬 생성기로 안전하게 동작합니다.',
      startTime: '시작 시간',
      backToThemes: '루트 테마로 돌아가기',
      backToMoods: '루트 무드로 돌아가기',
      chooseMood: '루트 무드 선택',
      reviewSelection: '선택 확인',
      confirmEyebrow: '루트 입력 확인',
      confirmTitle: '이대로 생성할까요?',
      confirmBody: '로컬 미리보기 루트를 만들기 전에 선택한 테마와 무드를 확인하세요.',
      selectedTheme: '테마',
      selectedDetail: '무드',
      selectedStart: '시작',
      adjustSelection: '선택 수정',
      personalizeFeed: '피드 개인화',
      personaSaved: '피드를 개인화했어요',
      generating: '루트 생성 중...',
      generate: '루트 생성',
      routeTitle: '{detail} 서울 루트',
      routeSummary: '{themeDescription} 총 {duration} 정도의 로컬 미리보기 루트입니다.',
      themes: {
        kpop: {
          label: 'K-pop 성지순례',
          description: '기획사 거리, 팬 포토 스팟, 음반 매장, 야경을 잇는 루트입니다.',
          details: {
            bts: { label: 'BTS', description: 'HYBE 주변, 굿즈 거리, 팬에게 익숙한 방문지.' },
            blackpink: { label: 'BLACKPINK', description: '쇼핑과 사진을 함께 즐기는 스타일 중심 코스.' },
            newjeans: { label: 'NewJeans', description: '레트로 감성, 카페, 사진 중심 장소.' },
            aespa: { label: 'aespa', description: '미래적인 공간과 에너지 있는 동네.' },
          },
        },
        drama: {
          label: 'K-드라마 장면',
          description: '궁궐, 골목, 시장, 영화 같은 산책 루트를 묶었습니다.',
          details: {
            palace: { label: '궁궐 드라마', description: '고전적인 촬영 무드가 있는 역사 서울.' },
            romance: { label: '로맨스 산책', description: '부드러운 풍경, 카페, 저녁 조명.' },
            street_food: { label: '길거리 음식 이야기', description: '시장과 간식이 많은 드라마 에너지.' },
            night: { label: '야간 에피소드', description: '다리, 타워, 밤의 도시 장면.' },
          },
        },
        mood: {
          label: '무드 여행',
          description: '사진, 속도, 휴식 시간을 고려한 감성 서울 루트입니다.',
          details: {
            cafe: { label: '카페 데이', description: '카페 거리, 디자인 숍, 느린 일정.' },
            photo: { label: '포토 워크', description: '색감과 질감이 좋은 쉬운 사진 스팟.' },
            healing: { label: '힐링', description: '공원, 강변 산책, 낮은 혼잡도.' },
            food: { label: '푸드 크롤', description: '시장, 간식, 저녁 식사에 좋은 동선.' },
          },
        },
        foodie: {
          label: '푸디 탐험',
          description: '길거리 음식, 시장, 디저트, 늦은 식사를 하루 동선으로 묶습니다.',
          details: {
            market: { label: '시장 맛보기', description: '오래된 골목, 한입 간식, 활기 있는 노점.' },
            dessert: { label: '디저트 홉', description: '카페, 베이커리, 달콤한 사진 스팟.' },
            night_food: { label: '나이트 푸드', description: '저녁 식사, 네온 거리, 쉬운 귀가 동선.' },
            local_table: { label: '로컬 밥상', description: '편안한 음식, 차, 느린 동네 산책.' },
          },
        },
        creator: {
          label: '콘텐츠 크리에이터',
          description: '사진 배경, 디자인 거리, 숏폼에 좋은 스팟을 잇습니다.',
          details: {
            reels: { label: '릴스 워크', description: '전환과 질감이 좋은 촘촘한 촬영 동선.' },
            fashion: { label: '패션 스트리트', description: '스타일 있는 동네와 부티크 쇼윈도.' },
            design: { label: '디자인 프레임', description: '건축, 갤러리, 깔끔한 구도의 장소.' },
            night_shot: { label: '야간 촬영', description: '조명, 반사, 스카이라인에 좋은 일정.' },
          },
        },
        history: {
          label: '역사 애호가',
          description: '궁궐, 한옥 골목, 박물관, 문화유산 중심의 도보 루트입니다.',
          details: {
            palace_day: { label: '궁궐 데이', description: '왕실 유적, 문, 한복 사진에 좋은 타이밍.' },
            hanok_walk: { label: '한옥 산책', description: '전통 골목, 차, 공예를 천천히 잇는 동선.' },
            museum: { label: '뮤지엄 루트', description: '날씨 영향을 덜 받는 실내 문화 코스.' },
            heritage_food: { label: '헤리티지 푸드', description: '오래된 서울 거리와 전통 시장 식사.' },
          },
        },
      },
    },
    docent: {
      title: 'AI 도슨트',
      eyebrow: '로컬 음성 가이드',
      localMode: '브라우저 음성',
      captionTitle: '자막',
      progressLabel: '스크립트 진행',
      progressValue: '{current}/{total} 구간',
      sectionIntroTitle: '소개',
      sectionBodyTitle: '상세 안내',
      sectionTagsTitle: '관찰 포인트',
      sectionOutroTitle: '다음 단계',
      play: '재생',
      pause: '일시정지',
      resume: '이어듣기',
      stop: '정지',
      replay: '다시 듣기',
      backToRoute: '루트로 돌아가기',
      textOnly: '텍스트 모드',
      audioUnavailable: '이 브라우저에서는 로컬 음성을 재생할 수 없어요.',
      fallbackName: '선택한 방문지',
      fallbackAddress: '주소 확인 중',
      fallbackCategory: '여행 방문지',
      defaultDescription: '현재 K-vibe 루트에 포함된 방문지입니다.',
      scriptIntro: '{name}은(는) 이번 루트의 {category} 방문지입니다.',
      scriptBody: '{description} 이곳에서는 약 {stayMinutes}분 정도 머물 예정입니다. 주소는 {address}입니다.',
      scriptTags: '이 장소를 볼 때 참고하면 좋은 키워드는 {tags}입니다.',
      scriptOutro: '잠시 주변 분위기를 느껴보고, 준비되면 다음 장소로 이동하세요.',
    },
    tutorial: {
      buttonLabel: '기능 안내',
      title: '기능 안내',
      subtitle: '현재 MVP에서 바로 사용할 수 있는 기능을 빠르게 확인하세요.',
      footer: '비용이나 권한이 필요한 연동은 자격 정보와 승인이 있기 전까지 비활성 상태로 둡니다.',
      steps: [
        {
          title: '지도',
          body: 'TourAPI 또는 로컬 대체 데이터로 주변 장소를 찾고, 카테고리 필터와 상세 보기, 루트 추가를 사용할 수 있습니다.',
          action: '지도 열기',
        },
        {
          title: '분석',
          body: 'YouTube 또는 Instagram URL로 플랫폼 감지를 확인합니다. YouTube mock 분석은 AI 비용 없이 동작합니다.',
          action: '분석해보기',
        },
        {
          title: '루트',
          body: '페르소나 기반 루트를 만들고 방문지를 수정하거나 순서를 바꾸고 공유 문구를 만들 수 있습니다.',
          action: '루트 만들기',
        },
        {
          title: '도슨트',
          body: '루트 방문지를 자막과 함께 로컬 음성 가이드로 열 수 있습니다. 유료 TTS API를 호출하지 않습니다.',
          action: '루트 열기',
        },
        {
          title: '레이더',
          body: '반경과 시설 유형을 바꿔 주변 편의시설을 찾고 데이터 출처 상태를 확인할 수 있습니다.',
          action: '레이더 열기',
        },
        {
          title: '프로필',
          body: '지금은 게스트 모드로 사용할 수 있고, Supabase 정보가 설정되면 계정 동기화와 저장 기록이 활성화됩니다.',
          action: '프로필 열기',
        },
      ],
    },
  },
  ja: {
    common: {
      appName: 'K-Vibe Tracker',
      signIn: 'ログイン',
      close: '閉じる',
      goBack: '戻る',
      changeLanguage: '言語を変更',
      openProfile: 'プロフィールを開く',
      avatarAlt: 'ユーザーアバター',
      unexpectedErrorTitle: '問題が発生しました',
      unexpectedErrorBody: '予期しないエラーが発生しました。もう一度お試しください。',
      reloadPage: 'ページを再読み込み',
      dismissNotification: '通知を閉じる',
    },
    login: {
      eyebrow: 'アカウント',
      title: 'K-Vibeにログイン',
      subtitle: 'Supabase設定後にルート保存と好みの同期ができます。',
      close: 'ログインを閉じる',
      continueGoogle: 'Googleで続ける',
      continueGuest: 'ゲストで続ける',
      availableWithoutLogin: 'ログインなしで使える機能',
      loginRequiredLater: '後でログインが必要: 保存ルート、共有履歴、アカウント同期',
      supabaseMissing: 'Supabase環境変数が設定されていません。ローカル開発ではゲストで続けられます。',
      failed: 'ログインに失敗しました。もう一度お試しください。',
      guestFeatures: [
        '地図探索とスポット検索',
        'SNSスポット分析',
        'ルート生成プレビュー',
        '便利施設レーダー',
      ],
    },
    landing: {
      eyebrow: 'ローカル優先の旅行ラボ',
      languageTitle: '言語を選択',
      description:
        'Kコンテンツに着想を得た場所、ルート、周辺ヘルプで韓国旅行を見つけましょう。キーが設定されている場合はTourAPIを使い、開発中は安全なローカルデータに戻ります。',
      start: 'K-Vibeを探す',
      guestNotice: '地図、分析、ルート、レーダーはログインなしで使えます。',
      developmentMode: '開発モード',
      developmentDescription:
        '外部サービスは明示的なキーや承認の後ろに置き、主要な流れはローカルでテスト可能に保ちます。',
      trendingLabel: 'おすすめ検索',
      trendingTags: ['聖水カフェ', '広蔵市場グルメ', '宮廷ドラマ', '弘大フォト', '漢江夜景'],
      features: {
        map: 'TourAPI周辺スポット',
        analyze: 'ローカル優先SNS分析',
        route: 'ペルソナルート作成',
        radar: '便利施設検索',
      },
    },
    homeFeed: {
      eyebrow: 'ソウルライブフィード',
      title: 'いま注目のKスポット',
      stories: {
        kpop: 'K-Pop',
        streetFood: 'ストリートフード',
        photoSpots: 'フォトスポット',
        nature: '自然',
        shopping: 'ショッピング',
      },
      refresh: 'フィード更新',
      openMap: '地図で開く',
      openPlaceDetail: '{name}の詳細を開く',
      empty: 'このフィルターに合うスポットはありません。',
      emptyHint: 'フィルターを戻すか、地図で探索を続けましょう。',
      showAll: 'すべて表示',
      exploreMap: '地図で探す',
      error: 'ホームフィードを読み込めませんでした',
      retry: '再試行',
      cachedFallback: 'ライブ更新に失敗したため、キャッシュ済みフィードを表示しています。',
      sourceTourapi: 'TourAPI',
      sourceCache: 'キャッシュ',
      sourceMock: 'Mock',
      personalizedFor: '{persona}向け',
    },
    nav: {
      map: '地図',
      analyze: '分析',
      route: 'ルート',
      radar: 'レーダー',
      profile: 'プロフィール',
    },
    categories: {
      all: 'すべて',
      cafe: 'カフェ',
      photo: '写真',
      fun: '遊び',
      culture: '文化',
      food: 'グルメ',
      stay: '宿泊',
      spot: 'スポット',
    },
    map: {
      seoulFallback: 'ソウル初期位置',
      currentLocation: '現在地',
      locationUnavailable: '位置情報の許可を利用できないため、保存済みまたは既定の位置を表示しています。',
      analysisResult: '分析結果の位置',
      searchPlaceholder: '場所を検索',
      loadingNearby: '周辺スポットを読み込み中',
      placesError: 'スポットを読み込めませんでした',
      retry: '再試行',
      noPlaces: 'スポットが見つかりません',
      noPlacesHint: '検索を消すかフィルターをリセットして、周辺スポットを再表示できます。',
      resetFilters: 'フィルターをリセット',
      nearbySpots: '周辺スポット',
      resultCount: '{count}件表示',
      addressPending: '住所確認中',
      addedFromMap: '地図から{category}スポットとして追加しました。',
      radiusLabel: 'km圏内',
      refreshLocation: '現在地を更新',
      openAnalyzer: 'SNS分析を開く',
      savedRouteTitle: '地図保存ルート',
      savedRouteSummary: '地図で選んだスポットから作成したカスタムルートです。',
      crowd: {
        low: '空き',
        mid: '通常',
        high: '混雑',
      },
    },
    placeDetail: {
      addToRoute: 'ルートに追加',
      addedToRoute: 'ルートに追加しました',
      save: '保存する',
      saved: '保存済み',
      removed: '保存スポットから削除しました',
      docent: 'ドーセント',
      details: '詳細',
      parking: '駐車',
      loadingDetail: 'TourAPI詳細を読み込み中',
      detailFallback: '詳細フォールバック',
      closeDetail: 'スポット詳細を閉じる',
      imagePreview: '{index}枚目の画像を表示',
      seenInTitle: '登場コンテンツ',
      seenInYoutube: 'YouTube動画 {count}件',
      seenInInstagram: 'Instagram投稿 {count}件',
      share: '共有',
      shared: '共有しました',
      copied: 'リンクをコピーしました',
      shareUnavailable: '共有できません',
      crowd: {
        low: '空き',
        mid: '通常',
        high: '混雑',
      },
    },
    analyze: {
      title: 'SNSスポット分析',
      subtitle:
        'YouTubeまたはInstagramのURLを貼り付けてください。YouTubeはAI承認前にローカルmock分析を使い、Instagramは検出のみ対応します。',
      inputPlaceholder: 'YouTubeまたはInstagram URLを貼り付け',
      invalidUrl: '対応しているYouTube URLではないようです。',
      unsupportedUrl: '対応しているYouTubeまたはInstagram URLを貼り付けてください。',
      youtubeSupported: 'YouTube対応',
      instagramPending: 'Instagram待機中',
      instagramPendingTitle: 'Instagram分析は承認待ちです',
      instagramPendingBody:
        'Instagramリンクは検出できますが、実際のスポット抽出は無料または承認済みprovider経路が用意されるまで保留します。',
      thumbnailAlt: 'YouTubeサムネイル',
      analyzeButton: 'スポットを分析',
      loadingButton: 'スポット分析中...',
      examplesLabel: 'サンプルURL',
      loadingTitle: '分析中',
      loadingEstimate: 'ローカル分析は通常数秒で完了します。AI worker有効時はコールドスタートで10-20秒かかる場合があります。',
      loadingColdStart: '時間がかかる場合、workerサーバーが起動中かもしれません。',
      loadingSteps: ['URLを確認中', '動画の文脈を読み取り中', '候補スポットを照合中', '地図用の結果を準備中'],
      errorTitle: '分析に失敗しました',
      retry: '再試行',
      foundSpots: '候補スポットを{count}件見つけました',
      emptyTitle: '明確なスポットが見つかりませんでした',
      emptyBody: '旅行Vlog、MVロケ地動画、または上のサンプルURLで再試行してください。',
      tryExample: 'サンプルYouTube URLを試す',
      sourceWorker: 'AI Worker',
      sourceMock: 'Mock',
      sourceCache: '以前の結果',
      confidence: '信頼度',
      map: '地図',
      viewOnMap: '地図で見る',
      buildRoute: 'ルート作成',
      localModeTitle: 'ローカル優先分析',
      localModeBody:
        '承認済みAI worker URLを明示的に設定するまでは、APIは決定的なmockスポット抽出を返します。',
      openVideo: '動画を開く',
      openPost: '投稿を開く',
      detectedAddress: 'YouTube分析から検出',
      routeTitle: 'SNS分析ルート',
      routeSummary: '{title}から作成したルート案です。',
      routeSaved: 'ルートを保存しました',
      routeSaveFailed: 'ルートを保存できません',
    },
    radar: {
      title: '便利施設レーダー',
      locationSeoul: 'ソウル既定位置',
      locationCurrent: '現在地',
      locationUnavailable: '位置情報の許可を利用できないため、保存済みまたは既定の位置の施設を表示しています。',
      found: '{count}件',
      refresh: '便利施設を更新',
      radius: '半径',
      sourceMock: 'Mock',
      mapTitle: 'レーダーマップ',
      mapSubtitle: '{radius}m圏内プレビュー',
      currentPosition: '現在地',
      openFacilityMap: 'Google Mapsで{name}を開く',
      filters: {
        all: 'すべて',
        restroom: 'トイレ',
        atm: 'ATM',
        medical: '医療',
        transit: '交通',
        cafe_toilet: 'カフェWC',
        pharmacy: '薬局',
        convenience: 'コンビニ',
        popup: 'ポップアップ',
      },
      facilityTypes: {
        restroom: 'トイレ',
        atm: 'ATM',
        medical: '医療',
        transit: '交通',
        pharmacy: '薬局',
        cafe_toilet: 'カフェトイレ',
        convenience: 'コンビニ',
        popup: 'ポップアップ',
      },
      errorTitle: '便利施設を読み込めませんでした',
      retry: '再試行',
      loading: '周辺の便利施設を検索中',
      emptyTitle: 'この半径内に施設がありません',
      emptyHint: '半径を広げるか、別のカテゴリを試してください。',
      expandRadius: '半径を広げる',
      closed: '営業時間外',
      twentyFourHours: '24時間',
      accessibleRestroom: 'バリアフリートイレあり',
      viewOnMap: '地図で見る',
      footer: '開発中はローカルmockデータを使用します。ライブ施設データは承認後に接続します。',
    },
    profile: {
      title: 'プロフィール',
      guestTitle: 'ゲスト旅行者',
      guestSubtitle: 'Supabaseなしでも地図、ルート、保存スポットをローカルゲストモードで使えます。',
      signInTitle: 'ログインすると旅を同期できます',
      signInDescription: 'Supabase設定後にアカウント同期が有効になります。',
      supabaseNotConfigured: 'Supabase未設定',
      supabaseDescription:
        'NEXT_PUBLIC_SUPABASE_URLとNEXT_PUBLIC_SUPABASE_ANON_KEYが提供されるまでログインは無効です。',
      savedPlaces: '保存スポット',
      noSavedPlaces: '保存したスポットはまだありません',
      noSavedPlacesHint: '地図でスポットを選び、ハートを押して保存できます。',
      savedRoutes: '保存ルート',
      noSavedRoutes: '保存済みルートはまだありません',
      noSavedRoutesHint: 'ルート生成または地図から追加するとローカルに保存されます。',
      createFirstRoute: '最初のルートを作成',
      currentRoute: '現在のローカルルート',
      editRoute: 'ルート編集',
      continueRoute: '続ける',
      routeProgress: '{done}/{total}完了',
      nextStop: '次のスポット',
      routeComplete: 'ルート完了',
      openMap: '地図で開く',
      openSavedDetail: '{name}の詳細を開く',
      openSavedDetailCta: '詳細を見る',
      openRouteDetail: '{name}ルートを開く',
      openRouteDetailCta: 'ルート詳細を開く',
      statsPlaces: 'スポット',
      statsRoutes: 'ルート',
      seeAll: 'すべて見る',
      showLess: '折りたたむ',
      settings: '設定',
      personaLabel: 'ペルソナ',
      personaUnset: '未選択',
      signInGoogle: 'Googleでログイン',
      signOut: 'ログアウト',
      routeStops: '{count}件',
    },
    route: {
      title: 'ルート',
      editableEyebrow: '編集できる旅程',
      helper: 'スポットをドラッグして順番を変更できます。ローカル保存は使え、アカウント同期は承認後に有効になります。',
      stops: 'スポット',
      done: '完了',
      walking: '徒歩',
      total: '合計',
      miniMapTitle: 'ルートミニマップ',
      miniMapSubtitle: '番号をタップするとGoogle Mapsでスポットを開きます。',
      travelSegment: '徒歩 {duration} · {distance}',
      transitSegment: '公共交通 {duration} · {distance}',
      travelSegmentBetween: '{from}から{to}まで',
      locationCardTitle: '現在距離',
      locationCardBody: '移動準備ができたら{name}までの現在距離を確認できます。',
      checkCurrentLocation: '位置を確認',
      checkingLocation: '確認中...',
      nextStopNear: '{name}まで{distance}以内です。準備できたらローカルドーセントを始めましょう。',
      nextStopFar: '{name}まで{distance}です。ルートに沿って進んでください。',
      locationPermissionDenied: '位置情報の許可が拒否されました。ルートは手動で使えます。',
      locationUnsupported: 'このブラウザでは位置確認を利用できません。',
      locationCheckError: '現在地を確認できませんでした。後でもう一度お試しください。',
      staySuffix: '分滞在',
      orderUpdated: 'ルート順を更新しました',
      stopRemoved: 'スポットを削除しました',
      sampleStopAdded: 'サンプルスポットを追加しました',
      stopCompleted: 'スポットを完了にしました',
      stopReopened: 'スポットを再開しました',
      routeCompleted: 'すべてのスポットが完了しました',
      addStopBeforeGuidance: 'ガイドを始める前にスポットを追加してください',
      shared: '共有しました',
      copiedSummary: 'ルート概要をコピーしました',
      shareUnavailable: '共有できません',
      sharedRouteLoaded: '共有ルートを読み込みました',
      addSampleStop: 'サンプルスポットを追加',
      openRouteMap: '地図で見る',
      openRouteMapTitle: 'アプリの地図でルート全体を見る',
      openDirections: '経路を開く',
      directionsOpened: '徒歩経路を開きました',
      startGuidance: 'ガイド開始',
      share: '共有',
      openStopDetail: 'アプリの地図で{name}の詳細を開く',
      openStopDetailTitle: 'スポット詳細を開く',
      openStopMap: 'Google Mapsで{name}を開く',
      openStopMapTitle: 'Google Mapsで開く',
      openDocent: '{name}のドーセントを開く',
      openDocentTitle: 'ドーセントを開く',
      completed: '完了',
      markComplete: '{name}を完了にする',
      markIncomplete: '{name}を再開する',
      markCompleteTitle: '完了にする',
      markIncompleteTitle: '再開する',
      moveStopUp: '{name}を上へ移動',
      moveStopDown: '{name}を下へ移動',
      moveStopUpTitle: '上へ移動',
      moveStopDownTitle: '下へ移動',
      removeStop: '{name}を削除',
      extraStop: {
        id: 'cheonggyecheon-stream',
        name: '清渓川',
        category: '散歩',
        address: 'ソウル鍾路区',
        description: '昔のソウルと夜の街歩きの間に入れやすい、自由度の高い散歩スポットです。',
        tags: ['散歩', '川'],
      },
    },
    persona: {
      previewEyebrow: 'ローカルルートプレビュー',
      createAnother: '別のルートを作成',
      stops: 'スポット',
      walking: '徒歩',
      total: '合計',
      editRoute: 'ルート編集',
      share: '共有',
      shared: '共有しました',
      copied: 'コピーしました',
      shareUnavailable: '共有できません',
      routeGenerated: 'ルートプレビューができました',
      routeSaved: '編集用ルートを保存しました',
      routeSaveUnavailable: 'ルートを保存できません',
      personaSaveUnavailable: 'フィードを個人化できません',
      generatorEyebrow: 'ルート生成',
      title: 'Kコンテンツの1日プランを作る',
      subtitle: 'テーマとムードを選んでください。有料AIの承認前は決定的なローカル生成で動作します。',
      startTime: '開始時間',
      backToThemes: 'ルートテーマへ戻る',
      backToMoods: 'ルートムードへ戻る',
      chooseMood: 'ルートのムードを選択',
      reviewSelection: '選択を確認',
      confirmEyebrow: 'ルート入力の確認',
      confirmTitle: 'この内容で生成しますか？',
      confirmBody: 'ローカルプレビュールートを作成する前に、選択したテーマとムードを確認してください。',
      selectedTheme: 'テーマ',
      selectedDetail: 'ムード',
      selectedStart: '開始',
      adjustSelection: '選択を修正',
      personalizeFeed: 'フィードを個人化',
      personaSaved: 'フィードを個人化しました',
      generating: 'ルート生成中...',
      generate: 'ルート生成',
      routeTitle: '{detail} ソウルルート',
      routeSummary: '{themeDescription} 所要時間{duration}のローカルプレビュールートです。',
      themes: {
        kpop: {
          label: 'K-pop聖地巡り',
          description: '事務所通り、ファン向け写真スポット、音楽ショップ、夜景を巡ります。',
          details: {
            bts: { label: 'BTS', description: 'HYBE周辺、グッズ通り、ファンにやさしいスポット。' },
            blackpink: { label: 'BLACKPINK', description: 'ショッピングと写真を楽しむスタイル重視のコース。' },
            newjeans: { label: 'NewJeans', description: 'レトロ、カフェ、写真映えを重視した場所。' },
            aespa: { label: 'aespa', description: '未来的なスポットと活気あるエリア。' },
          },
        },
        drama: {
          label: 'Kドラマの場面',
          description: '宮殿、路地、市場、映画のような散歩ルートです。',
          details: {
            palace: { label: '宮廷ドラマ', description: '歴史あるソウルで定番の撮影ムードを楽しむコース。' },
            romance: { label: 'ロマンス散歩', description: 'やわらかな風景、カフェ、夕方の灯り。' },
            street_food: { label: '屋台フード物語', description: '市場と軽食が多いドラマらしい雰囲気。' },
            night: { label: '夜のエピソード', description: '橋、タワー、夜の街を写すコース。' },
          },
        },
        mood: {
          label: 'ムード旅',
          description: '写真、歩くペース、休憩時間を考えたソウルルートです。',
          details: {
            cafe: { label: 'カフェデー', description: 'カフェ通り、デザインショップ、ゆっくりした進行。' },
            photo: { label: 'フォトウォーク', description: '色や質感がよく、撮りやすい写真スポット。' },
            healing: { label: 'ヒーリング', description: '公園、川沿いの散歩、混雑を抑えた場所。' },
            food: { label: 'フード巡り', description: '市場、軽食、夕食にも向いた動線。' },
          },
        },
        foodie: {
          label: 'フーディー探索',
          description: '屋台、市場、スイーツ、遅めの食事を歩きやすい1日にまとめます。',
          details: {
            market: { label: '市場テイスティング', description: '昔ながらの路地、軽い一口、活気ある屋台。' },
            dessert: { label: 'スイーツ巡り', description: 'カフェ、ベーカリー、甘い写真スポット。' },
            night_food: { label: '夜ごはん', description: '夕食、ネオンの通り、帰りやすい終点。' },
            local_table: { label: 'ローカル食卓', description: 'ほっとする食事、お茶、ゆっくりした街歩き。' },
          },
        },
        creator: {
          label: 'コンテンツクリエイター',
          description: '写真映えする背景、デザイン通り、ショート動画向きスポットを巡ります。',
          details: {
            reels: { label: 'リール散歩', description: '切り替えや質感を撮りやすいコンパクトな動線。' },
            fashion: { label: 'ファッション通り', description: 'スタイルのある街とブティックのショーウィンドウ。' },
            design: { label: 'デザインフレーム', description: '建築、ギャラリー、構図を作りやすい場所。' },
            night_shot: { label: '夜景ショット', description: '光、反射、スカイラインを撮りやすい進行。' },
          },
        },
        history: {
          label: '歴史好き',
          description: '宮殿、韓屋の路地、博物館、文化遺産中心の徒歩ルートです。',
          details: {
            palace_day: { label: '宮殿デー', description: '王宮、門、韓服写真に合うタイミング。' },
            hanok_walk: { label: '韓屋散歩', description: '伝統的な路地、お茶、工芸をゆっくり巡る動線。' },
            museum: { label: 'ミュージアムルート', description: '天候に左右されにくい屋内文化コース。' },
            heritage_food: { label: 'ヘリテージフード', description: '古いソウルの通りと昔ながらの市場ごはん。' },
          },
        },
      },
    },
    docent: {
      title: 'AIドーセント',
      eyebrow: 'ローカル音声ガイド',
      localMode: 'ブラウザ音声',
      captionTitle: '字幕',
      progressLabel: 'スクリプト進行',
      progressValue: '{current}/{total}セクション',
      sectionIntroTitle: '紹介',
      sectionBodyTitle: '詳細ガイド',
      sectionTagsTitle: '注目ポイント',
      sectionOutroTitle: '次のステップ',
      play: '再生',
      pause: '一時停止',
      resume: '再開',
      stop: '停止',
      replay: 'もう一度',
      backToRoute: 'ルートへ戻る',
      textOnly: 'テキストモード',
      audioUnavailable: 'このブラウザではローカル音声を再生できません。',
      fallbackName: '選択したスポット',
      fallbackAddress: '住所確認中',
      fallbackCategory: '旅行スポット',
      defaultDescription: '現在のK-vibeルートに含まれるスポットです。',
      scriptIntro: '{name}は今回のルートの{category}スポットです。',
      scriptBody: '{description} ここでは約{stayMinutes}分滞在する予定です。住所は{address}です。',
      scriptTags: 'このスポットの注目キーワードは{tags}です。',
      scriptOutro: '少し周囲の雰囲気を楽しんでから、次の場所へ進みましょう。',
    },
    tutorial: {
      buttonLabel: '機能ガイド',
      title: '機能ガイド',
      subtitle: '現在のMVPで使える機能をすばやく確認できます。',
      footer: '費用や権限が必要な連携は、認証情報と承認があるまで無効のままです。',
      steps: [
        {
          title: '地図',
          body: 'TourAPIまたはローカル代替データで周辺スポットを探し、カテゴリフィルタ、詳細表示、ルート追加が使えます。',
          action: '地図を開く',
        },
        {
          title: '分析',
          body: 'YouTubeまたはInstagram URLでプラットフォーム検出を試せます。YouTube mock分析はAI費用なしで動作します。',
          action: '分析を試す',
        },
        {
          title: 'ルート',
          body: 'ペルソナベースのルートを作り、スポット編集、並べ替え、共有テキスト作成ができます。',
          action: 'ルート作成',
        },
        {
          title: 'ドーセント',
          body: 'ルート内スポットを字幕付きローカル音声ガイドとして開けます。有料TTS APIは呼びません。',
          action: 'ルートを開く',
        },
        {
          title: 'レーダー',
          body: '半径と施設タイプを変えながら周辺の便利施設を探し、データソース状態を確認できます。',
          action: 'レーダーを開く',
        },
        {
          title: 'プロフィール',
          body: '今はゲストモードで利用でき、Supabase設定後にアカウント同期と保存履歴が有効になります。',
          action: 'プロフィール',
        },
      ],
    },
  },
  zh: {
    common: {
      appName: 'K-Vibe Tracker',
      signIn: '登录',
      close: '关闭',
      goBack: '返回',
      changeLanguage: '更改语言',
      openProfile: '打开我的',
      avatarAlt: '用户头像',
      unexpectedErrorTitle: '出现问题',
      unexpectedErrorBody: '发生了意外错误，请重试。',
      reloadPage: '重新加载页面',
      dismissNotification: '关闭通知',
    },
    login: {
      eyebrow: '账号',
      title: '登录K-Vibe',
      subtitle: '配置Supabase后，可以保存路线并同步偏好。',
      close: '关闭登录',
      continueGoogle: '使用Google继续',
      continueGuest: '以访客继续',
      availableWithoutLogin: '无需登录可用',
      loginRequiredLater: '稍后需要登录: 保存路线、分享历史、账号同步',
      supabaseMissing: 'Supabase环境变量未配置。本地开发时可以访客模式继续。',
      failed: '登录失败，请重试。',
      guestFeatures: [
        '地图探索和地点搜索',
        'SNS地点分析',
        '路线生成预览',
        '便利设施雷达',
      ],
    },
    landing: {
      eyebrow: '本地优先旅行实验室',
      languageTitle: '选择语言',
      description:
        '通过受K-content启发的地点、路线和周边旅行助手探索韩国。配置密钥后使用TourAPI地点数据，开发时保留安全的本地兜底数据。',
      start: '探索K-Vibe',
      guestNotice: '地图、分析、路线和雷达无需登录即可使用。',
      developmentMode: '开发模式',
      developmentDescription:
        '外部服务保留在明确密钥或审批之后，核心流程仍可在本地测试。',
      trendingLabel: '推荐搜索',
      trendingTags: ['圣水咖啡', '广藏市场美食', '宫廷剧', '弘大拍照', '汉江夜景'],
      features: {
        map: 'TourAPI周边地点',
        analyze: '本地优先SNS分析',
        route: '人格化路线规划',
        radar: '便利设施查找',
      },
    },
    homeFeed: {
      eyebrow: '首尔实时动态',
      title: '正在流行的K-spot',
      stories: {
        kpop: 'K-Pop',
        streetFood: '街头美食',
        photoSpots: '拍照点',
        nature: '自然',
        shopping: '购物',
      },
      refresh: '刷新动态',
      openMap: '在地图中打开',
      openPlaceDetail: '打开{name}详情',
      empty: '此筛选下没有找到地点。',
      emptyHint: '请重置筛选，或继续在地图中探索。',
      showAll: '显示全部',
      exploreMap: '探索地图',
      error: '无法加载首页动态',
      retry: '重试',
      cachedFallback: '实时刷新失败，正在显示缓存动态。',
      sourceTourapi: 'TourAPI',
      sourceCache: '缓存',
      sourceMock: 'Mock',
      personalizedFor: '为{persona}推荐',
    },
    nav: {
      map: '地图',
      analyze: '分析',
      route: '路线',
      radar: '雷达',
      profile: '我的',
    },
    categories: {
      all: '全部',
      cafe: '咖啡',
      photo: '拍照',
      fun: '玩乐',
      culture: '文化',
      food: '美食',
      stay: '住宿',
      spot: '地点',
    },
    map: {
      seoulFallback: '首尔默认位置',
      currentLocation: '当前位置',
      locationUnavailable: '无法使用位置权限，正在显示已保存位置或默认位置。',
      analysisResult: '分析结果位置',
      searchPlaceholder: '搜索地点',
      loadingNearby: '正在加载周边地点',
      placesError: '无法加载地点',
      retry: '重试',
      noPlaces: '未找到地点',
      noPlacesHint: '清除搜索或重置筛选，即可重新查看周边地点。',
      resetFilters: '重置筛选',
      nearbySpots: '附近地点',
      resultCount: '显示{count}个',
      addressPending: '正在确认地址',
      addedFromMap: '已从地图添加为{category}站点。',
      radiusLabel: 'km范围',
      refreshLocation: '刷新当前位置',
      openAnalyzer: '打开SNS分析',
      savedRouteTitle: '地图保存路线',
      savedRouteSummary: '由地图选择地点组成的自定义路线。',
      crowd: {
        low: '较空',
        mid: '普通',
        high: '拥挤',
      },
    },
    placeDetail: {
      addToRoute: '加入路线',
      addedToRoute: '已加入路线',
      save: '保存地点',
      saved: '已保存',
      removed: '已从保存地点移除',
      docent: '导览',
      details: '详情',
      parking: '停车',
      loadingDetail: '正在加载TourAPI详情',
      detailFallback: '详情兜底模式',
      closeDetail: '关闭地点详情',
      imagePreview: '查看第{index}张图片',
      seenInTitle: '出现于',
      seenInYoutube: 'YouTube视频 {count}个',
      seenInInstagram: 'Instagram帖子 {count}篇',
      share: '分享',
      shared: '已分享',
      copied: '已复制链接',
      shareUnavailable: '无法分享',
      crowd: {
        low: '较空',
        mid: '普通',
        high: '拥挤',
      },
    },
    analyze: {
      title: 'SNS地点分析',
      subtitle:
        '粘贴YouTube或Instagram URL。AI获批前YouTube会使用本地mock分析；Instagram目前只做链接识别。',
      inputPlaceholder: '粘贴YouTube或Instagram URL',
      invalidUrl: '这看起来不是支持的YouTube URL。',
      unsupportedUrl: '请粘贴支持的YouTube或Instagram URL。',
      youtubeSupported: 'YouTube可用',
      instagramPending: 'Instagram待接入',
      instagramPendingTitle: 'Instagram分析仍在审批后接入',
      instagramPendingBody:
        '应用现在可以识别Instagram链接，但实际地点提取会等到有免费或已批准的provider路径后再启用。',
      thumbnailAlt: 'YouTube缩略图',
      analyzeButton: '分析地点',
      loadingButton: '正在分析地点...',
      examplesLabel: '示例URL',
      loadingTitle: '正在分析',
      loadingEstimate: '本地分析通常几秒内完成。启用AI worker时，冷启动可能需要10-20秒。',
      loadingColdStart: '如果等待较久，worker服务器可能仍在启动。',
      loadingSteps: ['正在验证URL', '正在读取视频语境', '正在匹配候选地点', '正在准备地图结果'],
      errorTitle: '分析失败',
      retry: '重试',
      foundSpots: '找到{count}个候选地点',
      emptyTitle: '未找到明确地点',
      emptyBody: '请尝试旅行Vlog、MV取景地视频，或上方示例URL。',
      tryExample: '试用示例YouTube URL',
      sourceWorker: 'AI Worker',
      sourceMock: 'Mock',
      sourceCache: '历史结果',
      confidence: '置信度',
      map: '地图',
      viewOnMap: '在地图中查看',
      buildRoute: '生成路线',
      localModeTitle: '本地优先分析',
      localModeBody:
        '在明确配置已批准的AI worker URL之前，API会返回确定性的mock地点提取结果。',
      openVideo: '打开视频',
      openPost: '打开帖子',
      detectedAddress: '从YouTube分析中检测',
      routeTitle: 'SNS分析路线',
      routeSummary: '根据{title}生成的路线草稿。',
      routeSaved: '路线已保存',
      routeSaveFailed: '无法保存路线',
    },
    radar: {
      title: '便利设施雷达',
      locationSeoul: '首尔默认位置',
      locationCurrent: '当前位置',
      locationUnavailable: '无法使用位置权限，正在显示已保存位置或默认位置附近的设施。',
      found: '找到{count}个',
      refresh: '刷新便利设施',
      radius: '半径',
      sourceMock: 'Mock',
      mapTitle: '雷达地图',
      mapSubtitle: '{radius}m范围预览',
      currentPosition: '当前位置',
      openFacilityMap: '在Google Maps中打开{name}',
      filters: {
        all: '全部',
        restroom: '洗手间',
        atm: 'ATM',
        medical: '医疗',
        transit: '交通',
        cafe_toilet: '咖啡店WC',
        pharmacy: '药店',
        convenience: '便利店',
        popup: '快闪',
      },
      facilityTypes: {
        restroom: '洗手间',
        atm: 'ATM',
        medical: '医疗',
        transit: '交通',
        pharmacy: '药店',
        cafe_toilet: '咖啡店洗手间',
        convenience: '便利店',
        popup: '快闪店',
      },
      errorTitle: '无法加载便利设施',
      retry: '重试',
      loading: '正在搜索附近便利设施',
      emptyTitle: '此半径内未找到设施',
      emptyHint: '请扩大半径或尝试其他类别。',
      expandRadius: '扩大半径',
      closed: '已关闭',
      twentyFourHours: '24小时',
      accessibleRestroom: '有无障碍洗手间',
      viewOnMap: '在地图中查看',
      footer: '开发期间使用本地mock数据。实时设施数据源将在批准后接入。',
    },
    profile: {
      title: '我的',
      guestTitle: '访客旅行者',
      guestSubtitle: '没有Supabase也可以用本地访客模式使用地图、路线和保存地点。',
      signInTitle: '登录后同步旅行',
      signInDescription: '配置Supabase后会启用账号同步。',
      supabaseNotConfigured: 'Supabase未配置',
      supabaseDescription:
        '在提供NEXT_PUBLIC_SUPABASE_URL和NEXT_PUBLIC_SUPABASE_ANON_KEY之前，登录会保持关闭。',
      savedPlaces: '保存地点',
      noSavedPlaces: '还没有保存地点',
      noSavedPlacesHint: '打开地图，选择地点，然后点击爱心保存。',
      savedRoutes: '保存路线',
      noSavedRoutes: '还没有保存路线',
      noSavedRoutesHint: '生成路线或从地图添加地点后会保存在本地。',
      createFirstRoute: '创建第一条路线',
      currentRoute: '当前本地路线',
      editRoute: '编辑路线',
      continueRoute: '继续',
      routeProgress: '已完成{done}/{total}',
      nextStop: '下一站',
      routeComplete: '路线已完成',
      openMap: '在地图中打开',
      openSavedDetail: '打开{name}详情',
      openSavedDetailCta: '查看详情',
      openRouteDetail: '打开{name}路线',
      openRouteDetailCta: '打开路线详情',
      statsPlaces: '地点',
      statsRoutes: '路线',
      seeAll: '查看全部',
      showLess: '收起',
      settings: '设置',
      personaLabel: '画像',
      personaUnset: '未选择',
      signInGoogle: '使用Google登录',
      signOut: '退出登录',
      routeStops: '{count}站',
    },
    route: {
      title: '路线',
      editableEyebrow: '可编辑行程',
      helper: '拖动站点可以调整顺序。本地保存可用，账号同步会在凭据批准后启用。',
      stops: '站点',
      done: '完成',
      walking: '步行',
      total: '总计',
      miniMapTitle: '路线小地图',
      miniMapSubtitle: '点击编号可在Google Maps中打开该地点。',
      travelSegment: '步行 {duration} · {distance}',
      transitSegment: '公共交通 {duration} · {distance}',
      travelSegmentBetween: '从{from}到{to}',
      locationCardTitle: '当前位置距离',
      locationCardBody: '准备移动时，可查看你到{name}的当前距离。',
      checkCurrentLocation: '检查位置',
      checkingLocation: '检查中...',
      nextStopNear: '你距离{name}在{distance}以内。准备好后可开始本地导览。',
      nextStopFar: '距离{name}还有{distance}。请继续沿路线前进。',
      locationPermissionDenied: '位置权限已被拒绝。你仍可手动使用路线。',
      locationUnsupported: '此浏览器不支持位置检查。',
      locationCheckError: '无法检查当前位置。请稍后重试。',
      staySuffix: '分钟停留',
      orderUpdated: '路线顺序已更新',
      stopRemoved: '站点已删除',
      sampleStopAdded: '已添加示例站点',
      stopCompleted: '站点已标记完成',
      stopReopened: '站点已重新打开',
      routeCompleted: '所有站点已完成',
      addStopBeforeGuidance: '开始导览前请先添加站点',
      shared: '已分享',
      copiedSummary: '路线摘要已复制',
      shareUnavailable: '无法分享',
      sharedRouteLoaded: '已加载分享路线',
      addSampleStop: '添加示例站点',
      openRouteMap: '在地图中查看',
      openRouteMapTitle: '在应用地图中查看完整路线',
      openDirections: '打开路线导航',
      directionsOpened: '已打开步行路线',
      startGuidance: '开始导览',
      share: '分享',
      openStopDetail: '在应用地图中打开{name}详情',
      openStopDetailTitle: '打开地点详情',
      openStopMap: '在Google Maps中打开{name}',
      openStopMapTitle: '在Google Maps中打开',
      openDocent: '打开{name}导览',
      openDocentTitle: '打开导览',
      completed: '完成',
      markComplete: '标记{name}完成',
      markIncomplete: '重新打开{name}',
      markCompleteTitle: '标记完成',
      markIncompleteTitle: '重新打开',
      moveStopUp: '上移{name}',
      moveStopDown: '下移{name}',
      moveStopUpTitle: '上移',
      moveStopDownTitle: '下移',
      removeStop: '删除{name}',
      extraStop: {
        id: 'cheonggyecheon-stream',
        name: '清溪川',
        category: '散步',
        address: '首尔钟路区',
        description: '这是一处适合插入旧首尔与夜间街区之间的灵活散步站点。',
        tags: ['散步', '河流'],
      },
    },
    persona: {
      previewEyebrow: '本地路线预览',
      createAnother: '创建另一条路线',
      stops: '站点',
      walking: '步行',
      total: '总计',
      editRoute: '编辑路线',
      share: '分享',
      shared: '已分享',
      copied: '已复制',
      shareUnavailable: '无法分享',
      routeGenerated: '路线预览已准备好',
      routeSaved: '已保存可编辑路线',
      routeSaveUnavailable: '无法保存路线',
      personaSaveUnavailable: '无法个性化首页',
      generatorEyebrow: '路线生成器',
      title: '创建K-content一日路线',
      subtitle: '选择主题和路线氛围。付费AI批准前，会使用可预测的本地生成器。',
      startTime: '开始时间',
      backToThemes: '返回路线主题',
      backToMoods: '返回路线氛围',
      chooseMood: '选择路线氛围',
      reviewSelection: '确认选择',
      confirmEyebrow: '确认路线输入',
      confirmTitle: '要按此生成吗？',
      confirmBody: '创建本地预览路线前，请确认你选择的主题和氛围。',
      selectedTheme: '主题',
      selectedDetail: '氛围',
      selectedStart: '开始',
      adjustSelection: '修改选择',
      personalizeFeed: '个性化首页',
      personaSaved: '已个性化首页',
      generating: '正在生成路线...',
      generate: '生成路线',
      routeTitle: '{detail}首尔路线',
      routeSummary: '{themeDescription} 这是一条约{duration}的本地预览路线。',
      themes: {
        kpop: {
          label: 'K-pop朝圣',
          description: '经纪公司街区、粉丝拍照点、音乐商店和夜景。',
          details: {
            bts: { label: 'BTS', description: 'HYBE周边、周边商品街和适合粉丝的站点。' },
            blackpink: { label: 'BLACKPINK', description: '以购物和拍照为主的时尚路线。' },
            newjeans: { label: 'NewJeans', description: '复古、咖啡馆和适合拍照的地点。' },
            aespa: { label: 'aespa', description: '未来感空间和高能量街区。' },
          },
        },
        drama: {
          label: '韩剧情景',
          description: '宫殿、小巷、市场和电影感步行路线。',
          details: {
            palace: { label: '宫廷剧', description: '带有经典拍摄氛围的历史首尔。' },
            romance: { label: '浪漫散步', description: '柔和风景、咖啡馆和傍晚灯光。' },
            street_food: { label: '街头美食故事', description: '市场和小吃丰富的剧情能量。' },
            night: { label: '夜间篇章', description: '桥、塔和夜晚城市镜头。' },
          },
        },
        mood: {
          label: '氛围旅行',
          description: '兼顾节奏、拍照和休息时间的首尔路线。',
          details: {
            cafe: { label: '咖啡馆日', description: '咖啡街、设计小店和慢节奏行程。' },
            photo: { label: '拍照散步', description: '色彩、质感和轻松拍照点。' },
            healing: { label: '疗愈', description: '公园、河边散步和较低拥挤度。' },
            food: { label: '美食巡游', description: '市场、小吃和适合晚餐的动线。' },
          },
        },
        foodie: {
          label: '美食探索者',
          description: '把街头小吃、市场、甜点和夜间用餐串成适合步行的一天。',
          details: {
            market: { label: '市场试吃', description: '经典小巷、小份美食和热闹摊位。' },
            dessert: { label: '甜点跳点', description: '咖啡馆、面包店和甜美拍照点。' },
            night_food: { label: '夜间美食', description: '晚餐、霓虹街道和方便返程的终点。' },
            local_table: { label: '本地餐桌', description: '舒适餐食、茶和慢节奏街区。' },
          },
        },
        creator: {
          label: '内容创作者',
          description: '串联上镜背景、设计街区和适合短视频的地点。',
          details: {
            reels: { label: '短视频散步', description: '适合快速转场和质感镜头的紧凑动线。' },
            fashion: { label: '时尚街区', description: '有风格的街区和精品店橱窗。' },
            design: { label: '设计构图', description: '建筑、画廊和构图干净的场景。' },
            night_shot: { label: '夜景拍摄', description: '灯光、倒影和天际线友好的节奏。' },
          },
        },
        history: {
          label: '历史爱好者',
          description: '以宫殿、韩屋小巷、博物馆和文化遗产为核心的步行路线。',
          details: {
            palace_day: { label: '宫殿日', description: '王室遗迹、城门和适合韩服照片的时间。' },
            hanok_walk: { label: '韩屋散步', description: '传统小巷、茶和工艺的慢节奏动线。' },
            museum: { label: '博物馆路线', description: '不太受天气影响的室内文化路线。' },
            heritage_food: { label: '传统美食', description: '老首尔街道和经典市场餐食。' },
          },
        },
      },
    },
    docent: {
      title: 'AI导览',
      eyebrow: '本地语音导览',
      localMode: '浏览器语音',
      captionTitle: '字幕',
      progressLabel: '脚本进度',
      progressValue: '第{current}/{total}段',
      sectionIntroTitle: '介绍',
      sectionBodyTitle: '详细导览',
      sectionTagsTitle: '关注点',
      sectionOutroTitle: '下一步',
      play: '播放',
      pause: '暂停',
      resume: '继续',
      stop: '停止',
      replay: '重播',
      backToRoute: '返回路线',
      textOnly: '文本模式',
      audioUnavailable: '此浏览器无法播放本地语音。',
      fallbackName: '已选站点',
      fallbackAddress: '正在确认地址',
      fallbackCategory: '旅行站点',
      defaultDescription: '这是当前K-vibe路线中的一个站点。',
      scriptIntro: '{name}是这条路线中的{category}站点。',
      scriptBody: '{description} 你将在这里停留约{stayMinutes}分钟。地址是{address}。',
      scriptTags: '这个地点可以关注的关键词是{tags}。',
      scriptOutro: '先感受一下周围氛围，准备好后再前往下一站。',
    },
    tutorial: {
      buttonLabel: '功能指南',
      title: '功能指南',
      subtitle: '快速查看当前MVP可以使用的功能。',
      footer: '需要费用或权限的集成会保持关闭，直到凭据和审批明确完成。',
      steps: [
        {
          title: '地图',
          body: '使用TourAPI或本地兜底数据查找周边地点，支持分类筛选、查看详情和加入路线。',
          action: '打开地图',
        },
        {
          title: '分析',
          body: '粘贴YouTube或Instagram URL测试平台识别。YouTube mock分析无需AI费用也能运行。',
          action: '尝试分析',
        },
        {
          title: '路线',
          body: '生成基于人格的路线，编辑站点、调整顺序，并创建可分享的路线文本。',
          action: '创建路线',
        },
        {
          title: '导览',
          body: '把路线站点打开为带字幕的本地语音导览。它不会调用付费TTS API。',
          action: '打开路线',
        },
        {
          title: '雷达',
          body: '通过半径和设施类型筛选周边便利设施，并查看清晰的数据来源状态。',
          action: '打开雷达',
        },
        {
          title: '我的',
          body: '现在可使用访客模式；配置Supabase后会开启账号同步和保存历史。',
          action: '打开我的',
        },
      ],
    },
  },
} as const;

const PROFILE_SETTINGS_COPY: Record<UiLocale, ProfileSettingsCopy> = {
  en: {
    title: 'Settings',
    items: {
      language: { label: 'Language', value: 'Top switcher' },
      notifications: { label: 'Notifications', value: 'Permission-gated' },
      offlineMaps: { label: 'Offline maps', value: 'Not connected' },
      mapData: { label: 'Map data', value: 'TourAPI + fallback' },
    },
  },
  ko: {
    title: '설정',
    items: {
      language: { label: '언어', value: '상단 전환' },
      notifications: { label: '알림', value: '권한 필요' },
      offlineMaps: { label: '오프라인 지도', value: '미연결' },
      mapData: { label: '지도 데이터', value: 'TourAPI + 대체 데이터' },
    },
  },
  ja: {
    title: '設定',
    items: {
      language: { label: '言語', value: '上部で切替' },
      notifications: { label: '通知', value: '権限が必要' },
      offlineMaps: { label: 'オフライン地図', value: '未接続' },
      mapData: { label: '地図データ', value: 'TourAPI + 代替データ' },
    },
  },
  zh: {
    title: '设置',
    items: {
      language: { label: '语言', value: '顶部切换' },
      notifications: { label: '通知', value: '需要权限' },
      offlineMaps: { label: '离线地图', value: '未连接' },
      mapData: { label: '地图数据', value: 'TourAPI + 备用数据' },
    },
  },
};

const DOCENT_PROXIMITY_COPY: Record<UiLocale, DocentProximityCopy> = {
  en: {
    title: 'Arrival check',
    radiusLabel: '100m docent radius',
    checkButton: 'Check location',
    checking: 'Checking...',
    ready: 'You are within 100m. The local docent is ready.',
    far: 'You are outside the 100m radius. Recheck when you arrive.',
    distanceLabel: '{distance} from this stop',
    noCoordinates: 'This stop has no map coordinates yet.',
    unsupported: 'Location is not available in this browser.',
    denied: 'Location permission was denied. You can still play the guide manually.',
    timeout: 'Location took too long. Try again near the stop.',
    error: 'Location could not be checked. Try again later.',
  },
  ko: {
    title: '도착 확인',
    radiusLabel: '도슨트 반경 100m',
    checkButton: '위치 확인',
    checking: '확인 중...',
    ready: '100m 안에 있습니다. 로컬 도슨트를 시작할 수 있어요.',
    far: '아직 100m 반경 밖입니다. 도착한 뒤 다시 확인하세요.',
    distanceLabel: '방문지까지 {distance}',
    noCoordinates: '이 방문지는 아직 지도 좌표가 없습니다.',
    unsupported: '이 브라우저에서는 위치 확인을 사용할 수 없습니다.',
    denied: '위치 권한이 거부되었습니다. 안내는 수동으로 재생할 수 있어요.',
    timeout: '위치 확인 시간이 초과되었습니다. 방문지 근처에서 다시 시도하세요.',
    error: '위치를 확인하지 못했습니다. 잠시 후 다시 시도하세요.',
  },
  ja: {
    title: '到着チェック',
    radiusLabel: 'ドーセント半径100m',
    checkButton: '位置を確認',
    checking: '確認中...',
    ready: '100m圏内です。ローカルドーセントを開始できます。',
    far: 'まだ100m圏外です。到着後にもう一度確認してください。',
    distanceLabel: 'このスポットまで{distance}',
    noCoordinates: 'このスポットにはまだ地図座標がありません。',
    unsupported: 'このブラウザでは位置確認を利用できません。',
    denied: '位置情報の許可が拒否されました。ガイドは手動で再生できます。',
    timeout: '位置確認がタイムアウトしました。スポット付近でもう一度お試しください。',
    error: '位置を確認できませんでした。後でもう一度お試しください。',
  },
  zh: {
    title: '到达确认',
    radiusLabel: '导览触发半径100m',
    checkButton: '检查位置',
    checking: '检查中...',
    ready: '你已进入100m范围，可以开始本地导览。',
    far: '你还在100m范围外。到达后请再次检查。',
    distanceLabel: '距离此站点{distance}',
    noCoordinates: '此站点还没有地图坐标。',
    unsupported: '此浏览器无法使用位置检查。',
    denied: '位置权限已被拒绝。你仍可手动播放导览。',
    timeout: '位置检查超时。请在站点附近重试。',
    error: '无法检查当前位置。请稍后重试。',
  },
};

const LOCATION_STATUS_COPY: Record<UiLocale, LocationStatusCopy> = {
  en: {
    lastKnownLocation: 'Last known location',
  },
  ko: {
    lastKnownLocation: '마지막 위치',
  },
  ja: {
    lastKnownLocation: '最後の位置',
  },
  zh: {
    lastKnownLocation: '上次位置',
  },
};

const DATA_SOURCE_COPY: Record<UiLocale, DataSourceCopy> = {
  en: {
    tourApi: 'TourAPI',
    cache: 'Cache',
    mock: 'Mock',
  },
  ko: {
    tourApi: 'TourAPI',
    cache: '캐시',
    mock: 'Mock',
  },
  ja: {
    tourApi: 'TourAPI',
    cache: 'キャッシュ',
    mock: 'Mock',
  },
  zh: {
    tourApi: 'TourAPI',
    cache: '缓存',
    mock: 'Mock',
  },
};

const NETWORK_STATUS_COPY: Record<UiLocale, NetworkStatusCopy> = {
  en: {
    offlineTitle: 'Offline mode',
    offlineBody: 'Showing cached places, facilities, and app screens when available.',
  },
  ko: {
    offlineTitle: '오프라인 모드',
    offlineBody: '사용 가능한 캐시 장소, 편의시설, 앱 화면을 표시합니다.',
  },
  ja: {
    offlineTitle: 'オフラインモード',
    offlineBody: '利用可能なキャッシュ済みスポット、施設、アプリ画面を表示します。',
  },
  zh: {
    offlineTitle: '离线模式',
    offlineBody: '显示可用的缓存地点、设施和应用页面。',
  },
};

const PWA_INSTALL_COPY: Record<UiLocale, PwaInstallCopy> = {
  en: {
    title: 'Install K-Vibe',
    body: 'Add the app to your home screen for quicker access during trips.',
    install: 'Install',
    dismiss: 'Not now',
    close: 'Dismiss install prompt',
  },
  ko: {
    title: '홈 화면에 추가',
    body: '여행 중 빠르게 열 수 있도록 K-Vibe를 앱처럼 설치하세요.',
    install: '설치',
    dismiss: '나중에',
    close: '설치 안내 닫기',
  },
  ja: {
    title: 'ホーム画面に追加',
    body: '旅行中にすぐ開けるよう、K-Vibeをアプリのようにインストールできます。',
    install: 'インストール',
    dismiss: 'あとで',
    close: 'インストール案内を閉じる',
  },
  zh: {
    title: '添加到主屏幕',
    body: '将 K-Vibe 像应用一样安装，旅途中可以更快打开。',
    install: '安装',
    dismiss: '稍后',
    close: '关闭安装提示',
  },
};

export function normalizeUiLocale(value: string | string[] | undefined): UiLocale {
  const locale = Array.isArray(value) ? value[0] : value;
  return SUPPORTED_LOCALES.includes(locale as UiLocale) ? (locale as UiLocale) : 'en';
}

export function getUiCopy(locale: string | string[] | undefined) {
  return UI_COPY[normalizeUiLocale(locale)];
}

export function getProfileSettingsCopy(locale: string | string[] | undefined) {
  return PROFILE_SETTINGS_COPY[normalizeUiLocale(locale)];
}

export function getDocentProximityCopy(locale: string | string[] | undefined) {
  return DOCENT_PROXIMITY_COPY[normalizeUiLocale(locale)];
}

export function getLocationStatusCopy(locale: string | string[] | undefined) {
  return LOCATION_STATUS_COPY[normalizeUiLocale(locale)];
}

export function getDataSourceCopy(locale: string | string[] | undefined) {
  return DATA_SOURCE_COPY[normalizeUiLocale(locale)];
}

export function getNetworkStatusCopy(locale: string | string[] | undefined) {
  return NETWORK_STATUS_COPY[normalizeUiLocale(locale)];
}

export function getPwaInstallCopy(locale: string | string[] | undefined) {
  return PWA_INSTALL_COPY[normalizeUiLocale(locale)];
}
