export const SUPPORTED_LOCALES = ['en', 'ko', 'ja', 'zh'] as const;

export type UiLocale = (typeof SUPPORTED_LOCALES)[number];

export const LANGUAGE_NAMES: Record<UiLocale, string> = {
  en: 'English',
  ko: '한국어',
  ja: '日本語',
  zh: '中文',
};

const UI_COPY = {
  en: {
    common: {
      appName: 'K-Vibe Tracker',
      signIn: 'Sign in',
      close: 'Close',
    },
    landing: {
      eyebrow: 'Local-first travel lab',
      description:
        'Discover Korea through K-content inspired places, routes, and nearby travel helpers. TourAPI place data is used when a key is configured, with safe local fallbacks for development.',
      start: 'Explore K-Vibe',
      guestNotice: 'Map, Analyze, Route, and Radar work without login.',
      developmentMode: 'Development mode',
      developmentDescription:
        'External services stay behind explicit keys or approval gates, while core workflows remain testable locally.',
      trendingLabel: 'Trending prompts',
      trendingTags: ['Seongsu cafes', 'Gwangjang food', 'Palace drama', 'Hongdae photo', 'Han River night'],
      features: {
        map: 'TourAPI nearby spots',
        analyze: 'Local-first SNS extraction',
        route: 'Persona route planner',
        radar: 'Facility finder',
      },
    },
    nav: {
      map: 'Map',
      analyze: 'Analyze',
      route: 'Route',
      radar: 'Radar',
      profile: 'Profile',
    },
    categories: {
      all: 'All',
      cafe: 'Cafe',
      photo: 'Photo',
      fun: 'Fun',
      culture: 'Culture',
      food: 'Food',
      stay: 'Stay',
      spot: 'Spot',
    },
    map: {
      seoulFallback: 'Seoul fallback',
      currentLocation: 'Current location',
      analysisResult: 'Analysis result',
      searchPlaceholder: 'Search places',
      loadingNearby: 'Loading nearby places',
      placesError: 'Places could not be loaded',
      retry: 'Retry',
      noPlaces: 'No places found',
      addressPending: 'Address pending',
      addedFromMap: 'Added from the map as a {category} stop.',
      radiusLabel: 'km radius',
    },
    docent: {
      title: 'AI Docent',
      eyebrow: 'Local voice guide',
      localMode: 'Browser voice',
      captionTitle: 'Caption',
      play: 'Play',
      pause: 'Pause',
      resume: 'Resume',
      stop: 'Stop',
      replay: 'Replay',
      backToRoute: 'Back to route',
      textOnly: 'Text-only mode',
      audioUnavailable: 'This browser cannot play local speech here.',
      fallbackName: 'Selected stop',
      fallbackAddress: 'Address pending',
      fallbackCategory: 'Travel stop',
      defaultDescription: 'This stop is part of your current K-vibe route.',
      scriptIntro: '{name} is a {category} stop on your route.',
      scriptBody: '{description} You will spend about {stayMinutes} minutes here. The address is {address}.',
      scriptTags: 'Good cues for this stop: {tags}.',
      scriptOutro: 'Take a moment to look around, then continue when the timing feels right.',
    },
    tutorial: {
      buttonLabel: 'Feature guide',
      title: 'Feature Guide',
      subtitle: 'A quick tour of what you can use in this MVP.',
      footer: 'Paid or permission-gated integrations stay disabled until credentials are approved.',
      steps: [
        {
          title: 'Map',
          body: 'Find nearby places from TourAPI or mock fallback data, filter categories, inspect details, and add a spot to your route.',
        },
        {
          title: 'Analyze',
          body: 'Paste a YouTube URL to test the SNS extraction flow. Local mock analysis keeps the page usable without AI costs.',
        },
        {
          title: 'Route',
          body: 'Generate a persona-based route, edit stops, reorder the timeline, and share the plan text.',
        },
        {
          title: 'Docent',
          body: 'Open a route stop as a local voice guide with captions. It uses browser speech synthesis, not a paid TTS API.',
        },
        {
          title: 'Radar',
          body: 'Search nearby convenience facilities with radius/type filters and clear source hints.',
        },
        {
          title: 'Profile',
          body: 'Use guest mode now; Supabase sync and saved account history activate when credentials are configured.',
        },
      ],
    },
  },
  ko: {
    common: {
      appName: 'K-Vibe Tracker',
      signIn: '로그인',
      close: '닫기',
    },
    landing: {
      eyebrow: '로컬 우선 여행 실험실',
      description:
        'K-콘텐츠 감성의 장소, 루트, 주변 편의 정보를 통해 한국 여행을 발견하세요. 키가 설정되면 TourAPI 장소 데이터를 사용하고, 개발 중에는 안전한 로컬 대체 데이터를 유지합니다.',
      start: 'K-Vibe 둘러보기',
      guestNotice: '지도, 분석, 루트, 레이더는 로그인 없이 사용할 수 있어요.',
      developmentMode: '개발 모드',
      developmentDescription:
        '외부 서비스는 키나 승인 게이트 뒤에 두고, 핵심 흐름은 로컬에서 계속 테스트할 수 있게 유지합니다.',
      trendingLabel: '추천 탐색어',
      trendingTags: ['성수 카페', '광장시장 먹거리', '궁궐 드라마', '홍대 포토', '한강 야경'],
      features: {
        map: 'TourAPI 주변 장소',
        analyze: '로컬 우선 SNS 분석',
        route: '페르소나 루트 플래너',
        radar: '편의시설 찾기',
      },
    },
    nav: {
      map: '지도',
      analyze: '분석',
      route: '루트',
      radar: '레이더',
      profile: '프로필',
    },
    categories: {
      all: '전체',
      cafe: '카페',
      photo: '사진',
      fun: '즐길거리',
      culture: '문화',
      food: '음식',
      stay: '숙소',
      spot: '장소',
    },
    map: {
      seoulFallback: '서울 기본 위치',
      currentLocation: '현재 위치',
      analysisResult: '분석 결과 위치',
      searchPlaceholder: '장소 검색',
      loadingNearby: '주변 장소를 불러오는 중',
      placesError: '장소를 불러오지 못했습니다',
      retry: '다시 시도',
      noPlaces: '장소를 찾지 못했습니다',
      addressPending: '주소 확인 중',
      addedFromMap: '지도에서 {category} 방문지로 추가했어요.',
      radiusLabel: 'km 반경',
    },
    docent: {
      title: 'AI 도슨트',
      eyebrow: '로컬 음성 가이드',
      localMode: '브라우저 음성',
      captionTitle: '자막',
      play: '재생',
      pause: '일시정지',
      resume: '이어듣기',
      stop: '정지',
      replay: '다시 듣기',
      backToRoute: '루트로 돌아가기',
      textOnly: '텍스트 모드',
      audioUnavailable: '이 브라우저에서는 로컬 음성을 재생할 수 없어요.',
      fallbackName: '선택한 방문지',
      fallbackAddress: '주소 확인 중',
      fallbackCategory: '여행 방문지',
      defaultDescription: '현재 K-vibe 루트에 포함된 방문지입니다.',
      scriptIntro: '{name}은(는) 이번 루트의 {category} 방문지입니다.',
      scriptBody: '{description} 이곳에서는 약 {stayMinutes}분 정도 머물 예정입니다. 주소는 {address}입니다.',
      scriptTags: '이 장소를 볼 때 참고하면 좋은 키워드는 {tags}입니다.',
      scriptOutro: '잠시 주변 분위기를 느껴보고, 준비되면 다음 장소로 이동하세요.',
    },
    tutorial: {
      buttonLabel: '기능 안내',
      title: '기능 안내',
      subtitle: '현재 MVP에서 바로 사용할 수 있는 기능을 빠르게 확인하세요.',
      footer: '비용이나 권한이 필요한 연동은 자격 정보와 승인이 있기 전까지 비활성 상태로 둡니다.',
      steps: [
        {
          title: '지도',
          body: 'TourAPI 또는 로컬 대체 데이터로 주변 장소를 찾고, 카테고리 필터와 상세 보기, 루트 추가를 사용할 수 있습니다.',
        },
        {
          title: '분석',
          body: 'YouTube URL을 붙여 SNS 장소 추출 흐름을 테스트합니다. AI 비용 없이 로컬 mock 분석으로 화면이 동작합니다.',
        },
        {
          title: '루트',
          body: '페르소나 기반 루트를 만들고 방문지를 수정하거나 순서를 바꾸고 공유 문구를 만들 수 있습니다.',
        },
        {
          title: '도슨트',
          body: '루트 방문지를 자막과 함께 로컬 음성 가이드로 열 수 있습니다. 유료 TTS API를 호출하지 않습니다.',
        },
        {
          title: '레이더',
          body: '반경과 시설 유형을 바꿔 주변 편의시설을 찾고 데이터 출처 상태를 확인할 수 있습니다.',
        },
        {
          title: '프로필',
          body: '지금은 게스트 모드로 사용할 수 있고, Supabase 정보가 설정되면 계정 동기화와 저장 기록이 활성화됩니다.',
        },
      ],
    },
  },
  ja: {
    common: {
      appName: 'K-Vibe Tracker',
      signIn: 'ログイン',
      close: '閉じる',
    },
    landing: {
      eyebrow: 'ローカル優先の旅行ラボ',
      description:
        'Kコンテンツに着想を得た場所、ルート、周辺ヘルプで韓国旅行を見つけましょう。キーが設定されている場合はTourAPIを使い、開発中は安全なローカルデータに戻ります。',
      start: 'K-Vibeを探す',
      guestNotice: '地図、分析、ルート、レーダーはログインなしで使えます。',
      developmentMode: '開発モード',
      developmentDescription:
        '外部サービスは明示的なキーや承認の後ろに置き、主要な流れはローカルでテスト可能に保ちます。',
      trendingLabel: 'おすすめ検索',
      trendingTags: ['聖水カフェ', '広蔵市場グルメ', '宮廷ドラマ', '弘大フォト', '漢江夜景'],
      features: {
        map: 'TourAPI周辺スポット',
        analyze: 'ローカル優先SNS分析',
        route: 'ペルソナルート作成',
        radar: '便利施設検索',
      },
    },
    nav: {
      map: '地図',
      analyze: '分析',
      route: 'ルート',
      radar: 'レーダー',
      profile: 'プロフィール',
    },
    categories: {
      all: 'すべて',
      cafe: 'カフェ',
      photo: '写真',
      fun: '遊び',
      culture: '文化',
      food: 'グルメ',
      stay: '宿泊',
      spot: 'スポット',
    },
    map: {
      seoulFallback: 'ソウル初期位置',
      currentLocation: '現在地',
      analysisResult: '分析結果の位置',
      searchPlaceholder: '場所を検索',
      loadingNearby: '周辺スポットを読み込み中',
      placesError: 'スポットを読み込めませんでした',
      retry: '再試行',
      noPlaces: 'スポットが見つかりません',
      addressPending: '住所確認中',
      addedFromMap: '地図から{category}スポットとして追加しました。',
      radiusLabel: 'km圏内',
    },
    docent: {
      title: 'AIドーセント',
      eyebrow: 'ローカル音声ガイド',
      localMode: 'ブラウザ音声',
      captionTitle: '字幕',
      play: '再生',
      pause: '一時停止',
      resume: '再開',
      stop: '停止',
      replay: 'もう一度',
      backToRoute: 'ルートへ戻る',
      textOnly: 'テキストモード',
      audioUnavailable: 'このブラウザではローカル音声を再生できません。',
      fallbackName: '選択したスポット',
      fallbackAddress: '住所確認中',
      fallbackCategory: '旅行スポット',
      defaultDescription: '現在のK-vibeルートに含まれるスポットです。',
      scriptIntro: '{name}は今回のルートの{category}スポットです。',
      scriptBody: '{description} ここでは約{stayMinutes}分滞在する予定です。住所は{address}です。',
      scriptTags: 'このスポットの注目キーワードは{tags}です。',
      scriptOutro: '少し周囲の雰囲気を楽しんでから、次の場所へ進みましょう。',
    },
    tutorial: {
      buttonLabel: '機能ガイド',
      title: '機能ガイド',
      subtitle: '現在のMVPで使える機能をすばやく確認できます。',
      footer: '費用や権限が必要な連携は、認証情報と承認があるまで無効のままです。',
      steps: [
        {
          title: '地図',
          body: 'TourAPIまたはローカル代替データで周辺スポットを探し、カテゴリフィルタ、詳細表示、ルート追加が使えます。',
        },
        {
          title: '分析',
          body: 'YouTube URLでSNSスポット抽出フローを試せます。AI費用なしでローカルmock分析が動作します。',
        },
        {
          title: 'ルート',
          body: 'ペルソナベースのルートを作り、スポット編集、並べ替え、共有テキスト作成ができます。',
        },
        {
          title: 'ドーセント',
          body: 'ルート内スポットを字幕付きローカル音声ガイドとして開けます。有料TTS APIは呼びません。',
        },
        {
          title: 'レーダー',
          body: '半径と施設タイプを変えながら周辺の便利施設を探し、データソース状態を確認できます。',
        },
        {
          title: 'プロフィール',
          body: '今はゲストモードで利用でき、Supabase設定後にアカウント同期と保存履歴が有効になります。',
        },
      ],
    },
  },
  zh: {
    common: {
      appName: 'K-Vibe Tracker',
      signIn: '登录',
      close: '关闭',
    },
    landing: {
      eyebrow: '本地优先旅行实验室',
      description:
        '通过受K-content启发的地点、路线和周边旅行助手探索韩国。配置密钥后使用TourAPI地点数据，开发时保留安全的本地兜底数据。',
      start: '探索K-Vibe',
      guestNotice: '地图、分析、路线和雷达无需登录即可使用。',
      developmentMode: '开发模式',
      developmentDescription:
        '外部服务保留在明确密钥或审批之后，核心流程仍可在本地测试。',
      trendingLabel: '推荐搜索',
      trendingTags: ['圣水咖啡', '广藏市场美食', '宫廷剧', '弘大拍照', '汉江夜景'],
      features: {
        map: 'TourAPI周边地点',
        analyze: '本地优先SNS分析',
        route: '人格化路线规划',
        radar: '便利设施查找',
      },
    },
    nav: {
      map: '地图',
      analyze: '分析',
      route: '路线',
      radar: '雷达',
      profile: '我的',
    },
    categories: {
      all: '全部',
      cafe: '咖啡',
      photo: '拍照',
      fun: '玩乐',
      culture: '文化',
      food: '美食',
      stay: '住宿',
      spot: '地点',
    },
    map: {
      seoulFallback: '首尔默认位置',
      currentLocation: '当前位置',
      analysisResult: '分析结果位置',
      searchPlaceholder: '搜索地点',
      loadingNearby: '正在加载周边地点',
      placesError: '无法加载地点',
      retry: '重试',
      noPlaces: '未找到地点',
      addressPending: '正在确认地址',
      addedFromMap: '已从地图添加为{category}站点。',
      radiusLabel: 'km范围',
    },
    docent: {
      title: 'AI导览',
      eyebrow: '本地语音导览',
      localMode: '浏览器语音',
      captionTitle: '字幕',
      play: '播放',
      pause: '暂停',
      resume: '继续',
      stop: '停止',
      replay: '重播',
      backToRoute: '返回路线',
      textOnly: '文本模式',
      audioUnavailable: '此浏览器无法播放本地语音。',
      fallbackName: '已选站点',
      fallbackAddress: '正在确认地址',
      fallbackCategory: '旅行站点',
      defaultDescription: '这是当前K-vibe路线中的一个站点。',
      scriptIntro: '{name}是这条路线中的{category}站点。',
      scriptBody: '{description} 你将在这里停留约{stayMinutes}分钟。地址是{address}。',
      scriptTags: '这个地点可以关注的关键词是{tags}。',
      scriptOutro: '先感受一下周围氛围，准备好后再前往下一站。',
    },
    tutorial: {
      buttonLabel: '功能指南',
      title: '功能指南',
      subtitle: '快速查看当前MVP可以使用的功能。',
      footer: '需要费用或权限的集成会保持关闭，直到凭据和审批明确完成。',
      steps: [
        {
          title: '地图',
          body: '使用TourAPI或本地兜底数据查找周边地点，支持分类筛选、查看详情和加入路线。',
        },
        {
          title: '分析',
          body: '粘贴YouTube URL测试SNS地点提取流程。本地mock分析让页面无需AI费用也能运行。',
        },
        {
          title: '路线',
          body: '生成基于人格的路线，编辑站点、调整顺序，并创建可分享的路线文本。',
        },
        {
          title: '导览',
          body: '把路线站点打开为带字幕的本地语音导览。它不会调用付费TTS API。',
        },
        {
          title: '雷达',
          body: '通过半径和设施类型筛选周边便利设施，并查看清晰的数据来源状态。',
        },
        {
          title: '我的',
          body: '现在可使用访客模式；配置Supabase后会开启账号同步和保存历史。',
        },
      ],
    },
  },
} as const;

export function normalizeUiLocale(value: string | string[] | undefined): UiLocale {
  const locale = Array.isArray(value) ? value[0] : value;
  return SUPPORTED_LOCALES.includes(locale as UiLocale) ? (locale as UiLocale) : 'en';
}

export function getUiCopy(locale: string | string[] | undefined) {
  return UI_COPY[normalizeUiLocale(locale)];
}
